# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.api_post import ApiPost

class TestApiPost(unittest.TestCase):
    """ApiPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPost:
        """Test ApiPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPost`
        """
        model = ApiPost()
        if include_optional:
            return ApiPost(
                id = '',
                title = '',
                content = '',
                status = '',
                scheduled_for = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timezone = '',
                platforms = [
                    postzen.models.api_post_platform_result.ApiPostPlatformResult(
                        platform = 'twitter', 
                        account_id = postzen.models.api_post_account.ApiPostAccount(
                            _id = '', 
                            platform = 'twitter', 
                            username = '', 
                            display_name = '', 
                            is_active = True, ), 
                        status = 'draft', 
                        platform_post_url = '', 
                        error = '', )
                    ]
            )
        else:
            return ApiPost(
                id = '',
                title = '',
                content = '',
                status = '',
                scheduled_for = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timezone = '',
                platforms = [
                    postzen.models.api_post_platform_result.ApiPostPlatformResult(
                        platform = 'twitter', 
                        account_id = postzen.models.api_post_account.ApiPostAccount(
                            _id = '', 
                            platform = 'twitter', 
                            username = '', 
                            display_name = '', 
                            is_active = True, ), 
                        status = 'draft', 
                        platform_post_url = '', 
                        error = '', )
                    ],
        )
        """

    def testApiPost(self):
        """Test ApiPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
