# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.you_tube_settings import YouTubeSettings

class TestYouTubeSettings(unittest.TestCase):
    """YouTubeSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> YouTubeSettings:
        """Test YouTubeSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `YouTubeSettings`
        """
        model = YouTubeSettings()
        if include_optional:
            return YouTubeSettings(
                title = '',
                privacy_status = 'public',
                tags = None,
                category_id = '',
                made_for_kids = True,
                notify_subscribers = True
            )
        else:
            return YouTubeSettings(
        )
        """

    def testYouTubeSettings(self):
        """Test YouTubeSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
