# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.post_platform_settings import PostPlatformSettings

class TestPostPlatformSettings(unittest.TestCase):
    """PostPlatformSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPlatformSettings:
        """Test PostPlatformSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPlatformSettings`
        """
        model = PostPlatformSettings()
        if include_optional:
            return PostPlatformSettings(
                post_type = 'feed',
                collaborators = [
                    ''
                    ],
                user_tags = [
                    postzen.models.instagram_settings_user_tags_inner.InstagramSettings_userTags_inner(
                        username = '', 
                        x = 1.337, 
                        y = 1.337, )
                    ],
                first_comment = '',
                share_to_feed = True,
                link = '',
                reply_control = 'everyone',
                privacy_level = 'publicToEveryone',
                allow_comments = True,
                allow_duet = True,
                allow_stitch = True,
                disable_comment = True,
                disable_duet = True,
                disable_stitch = True,
                video_cover_timestamp_ms = 1.337,
                upload_as_draft = True,
                brand_content_toggle = True,
                brand_organic_toggle = True,
                visibility = 'PUBLIC',
                reply_settings = 'following',
                title = '',
                privacy_status = 'public',
                tags = None,
                category_id = '',
                made_for_kids = True,
                notify_subscribers = True,
                board_id = '',
                alt_text = ''
            )
        else:
            return PostPlatformSettings(
        )
        """

    def testPostPlatformSettings(self):
        """Test PostPlatformSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
