# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.accounts_list_response import AccountsListResponse

class TestAccountsListResponse(unittest.TestCase):
    """AccountsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountsListResponse:
        """Test AccountsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountsListResponse`
        """
        model = AccountsListResponse()
        if include_optional:
            return AccountsListResponse(
                accounts = [
                    postzen.models.account.Account(
                        _id = '', 
                        platform = 'twitter', 
                        provider_account_id = '', 
                        profile_id = postzen.models.account_profile_summary.AccountProfileSummary(
                            _id = '', 
                            name = '', 
                            slug = '', 
                            color = '', ), 
                        username = '', 
                        display_name = '', 
                        profile_url = '', 
                        avatar_url = '', 
                        status = 'connected', 
                        is_active = True, 
                        connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = postzen.models.pagination.Pagination(
                    page = 1, 
                    limit = 1, 
                    total = 0, 
                    total_pages = 0, )
            )
        else:
            return AccountsListResponse(
                accounts = [
                    postzen.models.account.Account(
                        _id = '', 
                        platform = 'twitter', 
                        provider_account_id = '', 
                        profile_id = postzen.models.account_profile_summary.AccountProfileSummary(
                            _id = '', 
                            name = '', 
                            slug = '', 
                            color = '', ), 
                        username = '', 
                        display_name = '', 
                        profile_url = '', 
                        avatar_url = '', 
                        status = 'connected', 
                        is_active = True, 
                        connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testAccountsListResponse(self):
        """Test AccountsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
