# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.api.posts_api import PostsApi


class TestPostsApi(unittest.TestCase):
    """PostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostsApi()

    def tearDown(self) -> None:
        pass

    def test_create_post(self) -> None:
        """Test case for create_post

        Create a post
        """
        pass


if __name__ == '__main__':
    unittest.main()
