# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.media_presign_request import MediaPresignRequest

class TestMediaPresignRequest(unittest.TestCase):
    """MediaPresignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaPresignRequest:
        """Test MediaPresignRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaPresignRequest`
        """
        model = MediaPresignRequest()
        if include_optional:
            return MediaPresignRequest(
                filename = '',
                content_type = 'image/jpeg',
                size = 0,
                profile_id = ''
            )
        else:
            return MediaPresignRequest(
                filename = '',
                content_type = 'image/jpeg',
        )
        """

    def testMediaPresignRequest(self):
        """Test MediaPresignRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
