# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.profile_update_request import ProfileUpdateRequest

class TestProfileUpdateRequest(unittest.TestCase):
    """ProfileUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileUpdateRequest:
        """Test ProfileUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileUpdateRequest`
        """
        model = ProfileUpdateRequest()
        if include_optional:
            return ProfileUpdateRequest(
                name = '0',
                description = '',
                color = '#62ECB0',
                is_default = True
            )
        else:
            return ProfileUpdateRequest(
        )
        """

    def testProfileUpdateRequest(self):
        """Test ProfileUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
