# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.api.connect_api import ConnectApi


class TestConnectApi(unittest.TestCase):
    """ConnectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectApi()

    def tearDown(self) -> None:
        pass

    def test_complete_connect(self) -> None:
        """Test case for complete_connect

        Complete an OAuth connection
        """
        pass

    def test_create_connect_url(self) -> None:
        """Test case for create_connect_url

        Create an OAuth connect URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
