# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.connect_complete_error_response import ConnectCompleteErrorResponse

class TestConnectCompleteErrorResponse(unittest.TestCase):
    """ConnectCompleteErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectCompleteErrorResponse:
        """Test ConnectCompleteErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectCompleteErrorResponse`
        """
        model = ConnectCompleteErrorResponse()
        if include_optional:
            return ConnectCompleteErrorResponse(
                error = '',
                error_description = ''
            )
        else:
            return ConnectCompleteErrorResponse(
                error = '',
        )
        """

    def testConnectCompleteErrorResponse(self):
        """Test ConnectCompleteErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
