# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.instagram_settings import InstagramSettings

class TestInstagramSettings(unittest.TestCase):
    """InstagramSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstagramSettings:
        """Test InstagramSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstagramSettings`
        """
        model = InstagramSettings()
        if include_optional:
            return InstagramSettings(
                post_type = 'feed',
                collaborators = [
                    ''
                    ],
                user_tags = [
                    postzen.models.instagram_settings_user_tags_inner.InstagramSettings_userTags_inner(
                        username = '', 
                        x = 1.337, 
                        y = 1.337, )
                    ],
                first_comment = '',
                share_to_feed = True
            )
        else:
            return InstagramSettings(
        )
        """

    def testInstagramSettings(self):
        """Test InstagramSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
