# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.public_platform_output import PublicPlatformOutput

class TestPublicPlatformOutput(unittest.TestCase):
    """PublicPlatformOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicPlatformOutput(self):
        """Test PublicPlatformOutput"""
        # inst = PublicPlatformOutput()

if __name__ == '__main__':
    unittest.main()
