# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.public_platform_input import PublicPlatformInput

class TestPublicPlatformInput(unittest.TestCase):
    """PublicPlatformInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicPlatformInput(self):
        """Test PublicPlatformInput"""
        # inst = PublicPlatformInput()

if __name__ == '__main__':
    unittest.main()
