# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.payment_required_error_details import PaymentRequiredErrorDetails

class TestPaymentRequiredErrorDetails(unittest.TestCase):
    """PaymentRequiredErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequiredErrorDetails:
        """Test PaymentRequiredErrorDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequiredErrorDetails`
        """
        model = PaymentRequiredErrorDetails()
        if include_optional:
            return PaymentRequiredErrorDetails(
                free_tier_account_limit = 1.337,
                current_account_count = 1.337,
                has_payment_method = True
            )
        else:
            return PaymentRequiredErrorDetails(
        )
        """

    def testPaymentRequiredErrorDetails(self):
        """Test PaymentRequiredErrorDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
