# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.account import Account

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                id = '',
                platform = 'twitter',
                provider_account_id = '',
                profile_id = postzen.models.account_profile_summary.AccountProfileSummary(
                    _id = '', 
                    name = '', 
                    slug = '', 
                    color = '', ),
                username = '',
                display_name = '',
                profile_url = '',
                avatar_url = '',
                status = 'connected',
                is_active = True,
                connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Account(
                id = '',
                platform = 'twitter',
                provider_account_id = '',
                profile_id = postzen.models.account_profile_summary.AccountProfileSummary(
                    _id = '', 
                    name = '', 
                    slug = '', 
                    color = '', ),
                username = '',
                display_name = '',
                status = 'connected',
                is_active = True,
                connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
