# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.connect_complete_response import ConnectCompleteResponse

class TestConnectCompleteResponse(unittest.TestCase):
    """ConnectCompleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectCompleteResponse:
        """Test ConnectCompleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectCompleteResponse`
        """
        model = ConnectCompleteResponse()
        if include_optional:
            return ConnectCompleteResponse(
                message = '',
                platform = 'twitter',
                profile_id = '',
                status = 'connected',
                missing_scopes = [
                    ''
                    ],
                connected_account_count = 0,
                accounts = [
                    postzen.models.account.Account(
                        _id = '', 
                        platform = 'twitter', 
                        provider_account_id = '', 
                        profile_id = postzen.models.account_profile_summary.AccountProfileSummary(
                            _id = '', 
                            name = '', 
                            slug = '', 
                            color = '', ), 
                        username = '', 
                        display_name = '', 
                        profile_url = '', 
                        avatar_url = '', 
                        status = 'connected', 
                        is_active = True, 
                        connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ConnectCompleteResponse(
                message = '',
                platform = 'twitter',
                profile_id = '',
                status = 'connected',
        )
        """

    def testConnectCompleteResponse(self):
        """Test ConnectCompleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
