# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_profile(self) -> None:
        """Test case for create_profile

        Create a profile
        """
        pass

    def test_delete_profile(self) -> None:
        """Test case for delete_profile

        Delete a profile
        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        Get a profile
        """
        pass

    def test_list_profiles(self) -> None:
        """Test case for list_profiles

        List profiles
        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        Update a profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
