# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.create_post_request import CreatePostRequest

class TestCreatePostRequest(unittest.TestCase):
    """CreatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePostRequest:
        """Test CreatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePostRequest`
        """
        model = CreatePostRequest()
        if include_optional:
            return CreatePostRequest(
                title = '',
                content = '',
                media_items = [
                    postzen.models.post_media_item.PostMediaItem(
                        url = '', 
                        title = '', )
                    ],
                platforms = [
                    postzen.models.create_post_target.CreatePostTarget(
                        platform = 'twitter', 
                        account_id = '', 
                        custom_content = '', 
                        settings = null, )
                    ],
                scheduled_for = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                publish_now = True,
                is_draft = True,
                timezone = 'UTC',
                tags = [
                    ''
                    ]
            )
        else:
            return CreatePostRequest(
        )
        """

    def testCreatePostRequest(self):
        """Test CreatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
