# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.profile_write_response import ProfileWriteResponse

class TestProfileWriteResponse(unittest.TestCase):
    """ProfileWriteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileWriteResponse:
        """Test ProfileWriteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileWriteResponse`
        """
        model = ProfileWriteResponse()
        if include_optional:
            return ProfileWriteResponse(
                message = '',
                profile = postzen.models.profile.Profile(
                    _id = '', 
                    user_id = '', 
                    name = '', 
                    description = '', 
                    color = '#62ECB0', 
                    is_default = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return ProfileWriteResponse(
                message = '',
                profile = postzen.models.profile.Profile(
                    _id = '', 
                    user_id = '', 
                    name = '', 
                    description = '', 
                    color = '#62ECB0', 
                    is_default = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testProfileWriteResponse(self):
        """Test ProfileWriteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
