# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from postzen.models.api_post_account import ApiPostAccount

class TestApiPostAccount(unittest.TestCase):
    """ApiPostAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPostAccount:
        """Test ApiPostAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPostAccount`
        """
        model = ApiPostAccount()
        if include_optional:
            return ApiPostAccount(
                id = '',
                platform = 'twitter',
                username = '',
                display_name = '',
                is_active = True
            )
        else:
            return ApiPostAccount(
                id = '',
                platform = 'twitter',
                username = '',
                display_name = '',
                is_active = True,
        )
        """

    def testApiPostAccount(self):
        """Test ApiPostAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
