"""Auto-generated endpoint surface tests.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_endpoint_tests.py` to regenerate.
"""

from __future__ import annotations


def test_all_spec_endpoints_are_available(client):
    expected = {
        "profiles": [
            "list_profiles",
            "create_profile",
            "get_profile",
            "update_profile",
            "delete_profile",
        ],
        "accounts": [
            "list_accounts",
            "disconnect_account",
            "get_pinterest_boards",
            "create_pinterest_board",
            "update_pinterest_boards",
        ],
        "connect": [
            "list_pinterest_boards_for_selection",
            "select_pinterest_board",
            "create_connect_url",
            "complete_connect",
        ],
        "media": [
            "create_media_presign",
            "upload_media_direct",
        ],
        "posts": [
            "bulk_upload_posts",
            "list_posts",
            "create_post",
            "get_post",
            "update_post",
            "delete_post",
            "list_post_comments",
            "list_post_reactions",
        ],
    }
    for resource_name, methods in expected.items():
        resource = getattr(client, resource_name)
        for method in methods:
            assert callable(getattr(resource, method))
            assert callable(getattr(resource, f'a{method}'))
