"""Auto-generated endpoint surface tests.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_endpoint_tests.py` to regenerate.
"""

from __future__ import annotations


def test_all_spec_endpoints_are_available(client):
    expected = {
        "profiles": [
            "list_profiles",
            "create_profile",
            "get_profile",
            "update_profile",
            "delete_profile",
        ],
        "accounts": [
            "list_accounts",
            "disconnect_account",
        ],
        "connect": [
            "create_connect_url",
            "complete_connect",
        ],
        "media": [
            "create_media_presign",
        ],
        "posts": [
            "create_post",
        ],
    }
    for resource_name, methods in expected.items():
        resource = getattr(client, resource_name)
        for method in methods:
            assert callable(getattr(resource, method))
            assert callable(getattr(resource, f'a{method}'))
