"""Auto-generated endpoint surface tests.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_endpoint_tests.py` to regenerate.
"""

from __future__ import annotations


def test_all_spec_endpoints_are_available(client):
    expected = {
        "profiles": [
            "list_profiles",
            "create_profile",
            "get_profile",
            "update_profile",
            "delete_profile",
        ],
        "accounts": [
            "list_accounts",
            "disconnect_account",
            "get_pinterest_boards",
            "create_pinterest_board",
            "update_pinterest_boards",
        ],
        "connect": [
            "list_pinterest_boards_for_selection",
            "select_pinterest_board",
            "create_connect_url",
            "complete_connect",
        ],
        "media": [
            "create_media_presign",
            "upload_media_direct",
        ],
        "posts": [
            "bulk_upload_posts",
            "list_posts",
            "create_post",
            "get_post",
            "update_post",
            "delete_post",
            "list_post_comments",
            "list_post_reactions",
        ],
        "inbox": [
            "list_inbox_post_comments",
            "reply_to_inbox_post",
            "delete_inbox_comment",
            "hide_inbox_comment",
            "unhide_inbox_comment",
            "list_inbox_conversations",
            "search_inbox_conversations",
            "get_inbox_conversation",
            "update_inbox_conversation",
            "mark_inbox_conversation_read",
            "list_inbox_conversation_messages",
            "send_inbox_message",
        ],
        "comment_automations": [
            "list_comment_automations",
            "create_comment_automation",
            "get_comment_automation",
            "update_comment_automation",
            "delete_comment_automation",
            "list_comment_automation_logs",
        ],
        "contacts": [
            "list_contacts",
            "create_contact",
            "bulk_create_contacts",
            "get_contact",
            "update_contact",
            "delete_contact",
            "get_contact_channels",
        ],
        "queues": [
            "list_queue_slots",
            "create_queue_slot",
            "update_queue_slot",
            "delete_queue_slot",
            "get_next_queue_slot",
            "preview_queue",
        ],
        "analytics": [
            "get_analytics",
            "get_post_timeline",
            "get_daily_metrics",
            "get_best_time_to_post",
            "get_follower_stats",
            "sync_external_posts",
        ],
        "api_keys": [
            "list_api_keys",
            "create_api_key",
            "delete_api_key",
        ],
        "webhooks": [
            "list_webhooks",
            "create_webhook",
            "get_webhook",
            "update_webhook",
            "delete_webhook",
            "test_webhook",
            "list_webhook_deliveries",
            "redeliver_webhook_delivery",
        ],
    }
    for resource_name, methods in expected.items():
        resource = getattr(client, resource_name)
        for method in methods:
            assert callable(getattr(resource, method))
            assert callable(getattr(resource, f'a{method}'))
