# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: str


class ConnectCompleteErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: Annotated[
        str,
        Field(
            description='Human-readable message, or a camelCase error code (for example `oauthCallbackFailed`) when the platform callback fails.'
        ),
    ]
    errorDescription: Annotated[
        str | None,
        Field(
            description='Additional detail reported by the platform, when available.'
        ),
    ] = None


class Details(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    freeTierAccountLimit: float | None = None
    currentAccountCount: float | None = None
    hasPaymentMethod: bool | None = None


class PaymentRequiredError(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: str
    code: Literal['paymentRequired']
    reason: Literal['freeTierExceeded', 'xRequiresPaymentMethod']
    documentationUrl: str
    dashboardUrl: str
    details: Details | None = None


class MessageResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str


class Profile(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id', description='PostZen profile id.')]
    userId: Annotated[str, Field(description='Owner user id.')]
    name: Annotated[str, Field(max_length=80)]
    description: Annotated[str | None, Field(max_length=240)] = None
    color: Annotated[
        str,
        Field(
            description='Hex color in `#rrggbb` format.', pattern='^#[0-9a-fA-F]{6}$'
        ),
    ]
    isDefault: bool
    createdAt: datetime


class ProfilesListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    profiles: list[Profile]


class ProfileResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    profile: Profile


class ProfileWriteResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str
    profile: Profile


class ProfileCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=80, min_length=1)]
    description: Annotated[str | None, Field(max_length=240)] = None
    color: Annotated[str | None, Field(pattern='^#[0-9a-fA-F]{6}$')] = '#ffeda0'


class ProfileUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    name: Annotated[str | None, Field(max_length=80, min_length=1)] = None
    description: Annotated[
        str | None,
        Field(
            description='Pass an empty string or `null` to clear the description.',
            max_length=240,
        ),
    ] = None
    color: Annotated[str | None, Field(pattern='^#[0-9a-fA-F]{6}$')] = None
    isDefault: Annotated[
        bool | None,
        Field(description='Set to `true` to make this the default profile.'),
    ] = None


class AccountProfileSummary(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    name: str
    slug: str
    color: str


class Account(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    platform: Literal[
        'twitter',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
    ]
    providerAccountId: str
    profileId: AccountProfileSummary
    username: str
    displayName: str
    profileUrl: str | None = None
    avatarUrl: str | None = None
    status: Literal['connected', 'needsReauth', 'disconnected', 'disabled']
    isActive: bool
    connectedAt: datetime
    lastSyncedAt: datetime | None = None


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1, le=100)]
    total: Annotated[int, Field(ge=0)]
    totalPages: Annotated[int, Field(ge=0)]


class AccountsListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    accounts: list[Account]
    pagination: Pagination | None = None


class ConnectStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    authUrl: Annotated[
        str,
        Field(description='URL to redirect the user to for platform authorization.'),
    ]
    state: Annotated[
        str, Field(description='OAuth state parameter generated by PostZen.')
    ]


class ConnectCompleteRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    code: Annotated[
        str, Field(description='OAuth authorization code returned by the platform.')
    ]
    state: Annotated[
        str, Field(description='State returned by `GET /v1/connect/{platform}`.')
    ]
    profileId: Annotated[
        str,
        Field(description='PostZen profile id used when the connection was initiated.'),
    ]


class ConnectCompleteResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str
    platform: Literal[
        'twitter',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
    ]
    profileId: str
    status: Literal['connected', 'needsReauth']
    missingScopes: list[str] | None = None
    connectedAccountCount: Annotated[int | None, Field(ge=0)] = None
    accounts: list[Account] | None = None


class MediaPresignRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    filename: Annotated[
        str, Field(description='Original file name. PostZen sanitizes it for storage.')
    ]
    contentType: Literal[
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp',
        'image/gif',
        'video/mp4',
        'video/mpeg',
        'video/quicktime',
        'video/avi',
        'video/x-msvideo',
        'video/webm',
        'video/x-m4v',
        'application/pdf',
    ]
    size: Annotated[
        int | None, Field(description='File size in bytes.', ge=0, le=5368709120)
    ] = None
    profileId: Annotated[
        str | None,
        Field(
            description='Optional profile scope. If provided, the API key must have access to the profile.'
        ),
    ] = None


class MediaPresignResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    uploadUrl: Annotated[
        str, Field(description='Use this URL for the direct file upload.')
    ]
    publicUrl: Annotated[str, Field(description='Use this URL in post `mediaItems`.')]
    key: str
    type: Literal['image', 'video', 'gif', 'document']


class PostMediaItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    url: Annotated[
        str,
        Field(
            description='PostZen-hosted `publicUrl` from `POST /v1/media/presign`, or an external image/video URL. External URLs are downloaded and re-hosted by PostZen; they must resolve to an image or video (PDF is not supported) of at most 100 MB.'
        ),
    ]
    title: Annotated[
        str | None, Field(description='Optional alt text/title for the media item.')
    ] = None


class UserTag(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    username: str
    x: float
    y: float


class InstagramSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    postType: Literal['feed', 'story', 'reel', 'carousel'] | None = 'feed'
    collaborators: list[str] | None = None
    userTags: list[UserTag] | None = None
    firstComment: str | None = None
    shareToFeed: bool | None = None


class FacebookSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    link: str | None = None
    firstComment: str | None = None


class ThreadsSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    replyControl: Literal['everyone', 'accountsYouFollow', 'mentionedOnly'] | None = (
        None
    )


class TikTokSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    privacyLevel: (
        Literal[
            'publicToEveryone', 'mutualFollowFriends', 'followerOfCreator', 'selfOnly'
        ]
        | None
    ) = None
    allowComments: bool | None = None
    allowDuet: bool | None = None
    allowStitch: bool | None = None
    disableComment: bool | None = None
    disableDuet: bool | None = None
    disableStitch: bool | None = None
    videoCoverTimestampMs: float | None = None
    uploadAsDraft: bool | None = None
    brandContentToggle: bool | None = None
    brandOrganicToggle: bool | None = None


class LinkedInSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    visibility: Literal['PUBLIC', 'CONNECTIONS'] | None = None


class XSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    replySettings: Literal['following', 'mentionedUsers'] | None = None


class YouTubeSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    title: str | None = None
    privacyStatus: Literal['public', 'unlisted', 'private'] | None = None
    tags: list[str] | str | None = None
    categoryId: str | None = None
    madeForKids: bool | None = None
    notifySubscribers: bool | None = None


class PinterestSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    boardId: Annotated[
        str | None, Field(description='Pinterest board to publish the pin to.')
    ] = None
    title: Annotated[str | None, Field(description='Pin title.')] = None
    link: Annotated[str | None, Field(description='Destination link for the pin.')] = (
        None
    )
    altText: str | None = None


class AltText(RootModel[str]):
    root: Annotated[str, Field(max_length=2000)]


class BlueskySettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    altTexts: Annotated[
        list[AltText] | None,
        Field(
            description='Alt text for each image, matched to the media by order. Each entry is limited to 2000 characters.'
        ),
    ] = None
    languages: Annotated[
        list[str] | None,
        Field(
            description='Up to 3 BCP-47 language codes (e.g. `en`, `pt-BR`) declaring the languages of the post text.',
            max_length=3,
        ),
    ] = None
    disableLinkCard: Annotated[
        bool | None,
        Field(
            description='When true, PostZen skips generating an external link preview card for the first URL in the post.'
        ),
    ] = None


class ApiPostAccount(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
    ]
    username: str
    displayName: str
    isActive: bool


class ApiPostPlatformResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
    ]
    accountId: ApiPostAccount
    status: Literal[
        'draft', 'scheduled', 'pending', 'publishing', 'published', 'failed', 'canceled'
    ]
    platformPostUrl: str | None = None
    error: str | None = None


class CreatePostTarget(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
    ]
    accountId: Annotated[
        str, Field(description='PostZen account id or provider account id.')
    ]
    customContent: Annotated[
        str | None, Field(description='Overrides shared `content` for this platform.')
    ] = None
    settings: Annotated[
        InstagramSettings
        | FacebookSettings
        | ThreadsSettings
        | TikTokSettings
        | LinkedInSettings
        | XSettings
        | YouTubeSettings
        | PinterestSettings
        | BlueskySettings
        | None,
        Field(
            description='Platform-specific publishing options. Unknown keys are ignored.'
        ),
    ] = None


class ApiPost(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    title: str | None
    content: str
    status: str
    scheduledFor: datetime | None
    timezone: str
    platforms: list[ApiPostPlatformResult]


class CreatePostResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    post: ApiPost
    message: Literal[
        'Post published successfully',
        'Post scheduled successfully',
        'Draft created successfully',
    ]


class CreatePostReplayResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    existingPost: ApiPost
    message: Literal['Post already exists for this request id']


class CreatePostRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    title: Annotated[
        str | None,
        Field(
            description='Internal post title. YouTube uses this as the fallback video title when `settings.title` is omitted.'
        ),
    ] = None
    content: Annotated[
        str | None,
        Field(
            description='Shared post text. Platform-specific validation still applies.'
        ),
    ] = ''
    mediaItems: Annotated[
        list[PostMediaItem] | None,
        Field(
            description='Duplicate URLs are removed before the post is created.',
            max_length=10,
        ),
    ] = None
    platforms: list[CreatePostTarget] | None = None
    scheduledFor: Annotated[
        datetime | None,
        Field(
            description='ISO 8601 date for scheduled posts. Must be at least 60 seconds in the future.'
        ),
    ] = None
    publishNow: Annotated[
        bool | None, Field(description='Publish synchronously where possible.')
    ] = None
    isDraft: Annotated[
        bool | None,
        Field(description='Create a draft. `platforms` is optional for drafts.'),
    ] = None
    timezone: str | None = 'UTC'
    tags: list[str] | None = None
