# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: str


class AnalyticsDate(RootModel[date_aliased | datetime]):
    root: Annotated[
        date_aliased | datetime,
        Field(description='A `YYYY-MM-DD` calendar date or ISO 8601 datetime.'),
    ]


class AnalyticsSource(RootModel[Literal['all', 'postzen', 'external']]):
    root: Literal['all', 'postzen', 'external'] = 'all'


class AnalyticsMetricTotals(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    impressions: float
    reach: float
    likes: float
    comments: float
    shares: float
    saves: float
    clicks: float
    views: float


class AnalyticsMetrics(AnalyticsMetricTotals):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    engagementRate: Annotated[
        float,
        Field(
            description='Interaction count divided by impressions, multiplied by 100 and rounded to two decimals.'
        ),
    ]
    lastUpdated: datetime | None


class AnalyticsMediaItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    type: str
    url: str
    thumbnail: str


class PlatformAnalytics(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    status: str
    platformPostId: str
    accountId: str
    accountUsername: str
    analytics: AnalyticsMetrics
    syncStatus: Literal['synced', 'pending', 'failed']
    platformPostUrl: str | None
    errorMessage: str | None


class AnalyticsPost(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    postId: str
    postzenPostId: str | None
    status: str
    content: str
    scheduledFor: datetime
    publishedAt: datetime
    analytics: AnalyticsMetrics
    platformAnalytics: list[PlatformAnalytics]
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    platformPostUrl: str | None
    isExternal: bool
    syncStatus: Literal['synced', 'pending', 'failed']
    message: str | None
    thumbnailUrl: str | None
    mediaType: Literal['image', 'video', 'text', 'carousel'] | None
    mediaItems: list[AnalyticsMediaItem]


class AnalyticsOverview(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    totalPosts: float
    totals: AnalyticsMetricTotals
    avgEngagementRate: float


class TimelineItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    date: date_aliased
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    platformPostId: str
    impressions: float
    reach: float
    likes: float
    comments: float
    shares: float
    saves: float
    clicks: float
    views: float


class PostTimelineResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    postId: str
    timeline: list[TimelineItem]


class DailyDatum(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    date: date_aliased
    postCount: float
    platforms: dict[str, float]
    metrics: AnalyticsMetricTotals


class PlatformBreakdownItem(AnalyticsMetricTotals):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    postCount: float


class DailyMetricsResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    dailyData: list[DailyDatum]
    platformBreakdown: list[PlatformBreakdownItem]


class Slot(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    day_of_week: Annotated[
        int, Field(description='UTC day of week, where 0 is Sunday.', ge=0, le=6)
    ]
    hour: Annotated[int, Field(ge=0, le=23)]
    avg_engagement: float
    post_count: float


class BestTimeResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    slots: list[Slot]


class Account(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    username: str
    currentFollowers: float
    growth: float
    growthPercentage: float
    dataPoints: float


class Stat(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    date: date_aliased
    followers: float


class DateRange(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    from_: Annotated[datetime, Field(alias='from')]
    to: datetime


class FollowerStatsResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    accounts: list[Account]
    stats: dict[str, list[Stat]]
    dateRange: DateRange
    granularity: Literal['daily', 'weekly', 'monthly']


class SyncExternalPostsRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    accountId: str
    url: Annotated[
        str | None, Field(description='Optional platform post URL to locate.')
    ] = None
    postId: Annotated[
        str | None, Field(description='Optional platform post id to locate.')
    ] = None


class ExternalSyncedPost(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    platformPostId: str
    platformPostUrl: str
    content: str
    publishedAt: datetime
    mediaType: str
    mediaUrl: str
    thumbnailUrl: str
    mediaItems: list[AnalyticsMediaItem]
    analytics: AnalyticsMetrics


class Synced(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    postsFound: float
    postsSynced: float
    skipped: bool


class SyncExternalPostsResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    synced: Synced
    found: bool
    post: ExternalSyncedPost | None
    posts: list[ExternalSyncedPost]


class ConnectCompleteErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: Annotated[
        str,
        Field(
            description='Human-readable message, or a camelCase error code (for example `oauthCallbackFailed`) when the platform callback fails.'
        ),
    ]
    errorDescription: Annotated[
        str | None,
        Field(
            description='Additional detail reported by the platform, when available.'
        ),
    ] = None


class Details(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    freeTierAccountLimit: float | None = None
    currentAccountCount: float | None = None
    hasPaymentMethod: bool | None = None


class PaymentRequiredError(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: str
    code: Literal['paymentRequired']
    reason: Literal['freeTierExceeded', 'xRequiresPaymentMethod']
    documentationUrl: str
    dashboardUrl: str
    details: Details | None = None


class MessageResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str


class Profile(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id', description='PostZen profile id.')]
    userId: Annotated[str, Field(description='Owner user id.')]
    name: Annotated[str, Field(max_length=80)]
    description: Annotated[str | None, Field(max_length=240)] = None
    color: Annotated[
        str,
        Field(
            description='Hex color in `#rrggbb` format.', pattern='^#[0-9a-fA-F]{6}$'
        ),
    ]
    isDefault: bool
    createdAt: datetime


class ProfilesListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    profiles: list[Profile]


class ProfileResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    profile: Profile


class ProfileWriteResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str
    profile: Profile


class ProfileCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=80, min_length=1)]
    description: Annotated[str | None, Field(max_length=240)] = None
    color: Annotated[str | None, Field(pattern='^#[0-9a-fA-F]{6}$')] = '#ffeda0'


class ProfileUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    name: Annotated[str | None, Field(max_length=80, min_length=1)] = None
    description: Annotated[
        str | None,
        Field(
            description='Pass an empty string or `null` to clear the description.',
            max_length=240,
        ),
    ] = None
    color: Annotated[str | None, Field(pattern='^#[0-9a-fA-F]{6}$')] = None
    isDefault: Annotated[
        bool | None,
        Field(description='Set to `true` to make this the default profile.'),
    ] = None


class AccountProfileSummary(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    name: str
    slug: str
    color: str


class Account1(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    platform: Literal[
        'twitter',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    providerAccountId: str
    profileId: AccountProfileSummary
    username: str
    displayName: str
    profileUrl: str | None = None
    avatarUrl: str | None = None
    status: Literal['connected', 'needsReauth', 'disconnected', 'disabled']
    isActive: bool
    connectedAt: datetime
    lastSyncedAt: datetime | None = None


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    page: Annotated[int, Field(ge=1)]
    limit: Annotated[int, Field(ge=1, le=100)]
    total: Annotated[int, Field(ge=0)]
    totalPages: Annotated[int, Field(ge=0)]


class AccountsListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    accounts: list[Account1]
    pagination: Pagination | None = None


class RateLimitError(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    error: Literal['rate_limited']
    retryAfter: Annotated[
        int, Field(description='Number of seconds to wait before retrying.', ge=1)
    ]


class ConnectStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    authUrl: Annotated[
        str,
        Field(description='URL to redirect the user to for platform authorization.'),
    ]
    state: Annotated[
        str, Field(description='OAuth state parameter generated by PostZen.')
    ]


class ConnectCompleteRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    code: Annotated[
        str, Field(description='OAuth authorization code returned by the platform.')
    ]
    state: Annotated[
        str, Field(description='State returned by `GET /v1/connect/{platform}`.')
    ]
    profileId: Annotated[
        str,
        Field(description='PostZen profile id used when the connection was initiated.'),
    ]


class ConnectCompleteResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str
    platform: Literal[
        'twitter',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    profileId: str
    status: Literal['connected', 'needsReauth']
    missingScopes: list[str] | None = None
    connectedAccountCount: Annotated[int | None, Field(ge=0)] = None
    accounts: list[Account1] | None = None


class MediaPresignRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    filename: Annotated[
        str, Field(description='Original file name. PostZen sanitizes it for storage.')
    ]
    contentType: Literal[
        'image/jpeg',
        'image/jpg',
        'image/png',
        'image/webp',
        'image/gif',
        'video/mp4',
        'video/mpeg',
        'video/quicktime',
        'video/avi',
        'video/x-msvideo',
        'video/webm',
        'video/x-m4v',
        'application/pdf',
    ]
    size: Annotated[
        int | None, Field(description='File size in bytes.', ge=0, le=5368709120)
    ] = None
    profileId: Annotated[
        str | None,
        Field(
            description='Optional profile scope. If provided, the API key must have access to the profile.'
        ),
    ] = None


class MediaPresignResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    uploadUrl: Annotated[
        str, Field(description='Use this URL for the direct file upload.')
    ]
    publicUrl: Annotated[str, Field(description='Use this URL in post `mediaItems`.')]
    key: str
    type: Literal['image', 'video', 'gif', 'document']


class PostMediaItem(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    url: Annotated[
        str,
        Field(
            description='PostZen-hosted `publicUrl` from `POST /v1/media/presign`, or an external image/video URL. External URLs are downloaded and re-hosted by PostZen; they must resolve to an image or video (PDF is not supported) of at most 100 MB.'
        ),
    ]
    title: Annotated[
        str | None, Field(description='Optional alt text/title for the media item.')
    ] = None


class UserTag(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    username: str
    x: float
    y: float


class InstagramSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    postType: Annotated[
        Literal['feed', 'story', 'reel', 'carousel'] | None,
        Field(
            description='Instagram post format. `feed` (default) and `story` publish a single media item; `reel` publishes a single video; `carousel` publishes 2–10 ordered media items and may mix images and videos. Sending multiple media items with `feed` returns a validation error directing you to `carousel`.'
        ),
    ] = 'feed'
    collaborators: Annotated[
        list[str] | None,
        Field(
            description='Up to three Instagram usernames to invite as collaborators. Supported on feed, reel, and carousel posts.'
        ),
    ] = None
    userTags: Annotated[
        list[UserTag] | None,
        Field(
            description='Photo tags with relative `x`/`y` coordinates from 0 to 1. Feed posts only — user tags are not supported on carousels, reels, or stories.'
        ),
    ] = None
    firstComment: Annotated[
        str | None,
        Field(
            description='Posts a first comment after publishing. Supported on feed, reel, and carousel posts. Maximum 2,200 characters.'
        ),
    ] = None
    shareToFeed: Annotated[
        bool | None,
        Field(
            description='Reels only. Defaults to `true`. Set to `false` to keep the reel off the profile feed.'
        ),
    ] = None


class FacebookSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    link: str | None = None
    firstComment: str | None = None


class ThreadsSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    replyControl: Literal['everyone', 'accountsYouFollow', 'mentionedOnly'] | None = (
        None
    )


class TikTokSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    privacyLevel: (
        Literal[
            'publicToEveryone', 'mutualFollowFriends', 'followerOfCreator', 'selfOnly'
        ]
        | None
    ) = None
    allowComments: bool | None = None
    allowDuet: bool | None = None
    allowStitch: bool | None = None
    disableComment: bool | None = None
    disableDuet: bool | None = None
    disableStitch: bool | None = None
    videoCoverTimestampMs: float | None = None
    uploadAsDraft: bool | None = None
    brandContentToggle: bool | None = None
    brandOrganicToggle: bool | None = None


class LinkedInSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    visibility: Literal['PUBLIC', 'CONNECTIONS'] | None = None
    videoTitle: Annotated[
        str | None,
        Field(
            description='Optional title for video posts, shown on the LinkedIn video player. Ignored for non-video posts.',
            max_length=200,
        ),
    ] = None


class XSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    replySettings: Literal['following', 'mentionedUsers'] | None = None


class YouTubeSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    title: str | None = None
    privacyStatus: Literal['public', 'unlisted', 'private'] | None = None
    tags: list[str] | str | None = None
    categoryId: str | None = None
    madeForKids: bool | None = None
    notifySubscribers: bool | None = None


class PinterestSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    boardId: Annotated[str, Field(description='Pinterest board to publish the pin to.')]
    title: Annotated[str | None, Field(description='Pin title.')] = None
    link: Annotated[str | None, Field(description='Destination link for the pin.')] = (
        None
    )
    altText: str | None = None


class AltText(RootModel[str]):
    root: Annotated[str, Field(max_length=2000)]


class BlueskySettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    altTexts: Annotated[
        list[AltText] | None,
        Field(
            description='Alt text for each image, matched to the media by order. Each entry is limited to 2000 characters.'
        ),
    ] = None
    languages: Annotated[
        list[str] | None,
        Field(
            description='Up to 3 BCP-47 language codes (e.g. `en`, `pt-BR`) declaring the languages of the post text.',
            max_length=3,
        ),
    ] = None
    disableLinkCard: Annotated[
        bool | None,
        Field(
            description='When true, PostZen skips generating an external link preview card for the first URL in the post.'
        ),
    ] = None


class TelegramSettings(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    parseMode: Annotated[
        Literal['html', 'markdownv2'] | None,
        Field(
            description='Formatting mode for the message or caption. Omit to send plain text, which is the default. `html` is recommended: it only requires escaping `<`, `>`, and `&`, whereas `markdownv2` requires escaping every one of `_ * [ ] ( ) ~ ` > # + - = | { } . !` and rejects the whole message otherwise.'
        ),
    ] = None
    disableNotification: Annotated[
        bool | None,
        Field(
            description='When true, members receive the post silently, with no sound or vibration.'
        ),
    ] = None
    disableLinkPreview: Annotated[
        bool | None,
        Field(
            description='When true, suppresses the link preview card for URLs in the text. Applies to text-only posts; a post with media has no link preview.'
        ),
    ] = None
    protectContent: Annotated[
        bool | None,
        Field(
            description='When true, Telegram blocks forwarding and saving of the post.'
        ),
    ] = None


class ApiPostAccount(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    username: str
    displayName: str
    isActive: bool


class ApiKeyProfileRef(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id', description='PostZen profile id.')]
    name: str
    color: Annotated[str, Field(description='Hex color in `#rrggbb` format.')]


class ApiKey(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    id: Annotated[str, Field(description='API key id.')]
    name: Annotated[str, Field(description='Human-readable label.')]
    keyPreview: Annotated[
        str,
        Field(
            description='Masked preview of the key, for example `pzn_live_a1b2c3d4e...`. The full key is never retrievable after creation.'
        ),
    ]
    createdAt: datetime
    lastUsedAt: Annotated[
        datetime | None,
        Field(
            description='Last time the key authenticated a request, or `null` if it has never been used.'
        ),
    ]
    scope: Annotated[
        Literal['full', 'profiles'],
        Field(
            description='`full` grants access to all profiles; `profiles` restricts the key to `profileIds`.'
        ),
    ]
    profileIds: Annotated[
        list[ApiKeyProfileRef],
        Field(
            description='Profiles the key is restricted to. Empty for full-scope keys.'
        ),
    ]
    permission: Annotated[
        Literal['read-write', 'read'],
        Field(
            description='`read` keys may only call `GET` endpoints; `read-write` keys may call every endpoint.'
        ),
    ]


class ApiKeyWithSecret(ApiKey):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    key: Annotated[
        str,
        Field(
            description='The full API key. Shown only once in the create response — store it securely, as it cannot be retrieved again.'
        ),
    ]


class ApiKeysListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    apiKeys: list[ApiKey]


class ApiKeyCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    name: Annotated[
        str,
        Field(
            description='Human-readable label for the key.',
            max_length=100,
            min_length=1,
        ),
    ]
    scope: Annotated[
        Literal['full', 'profiles'] | None,
        Field(
            description='`full` grants access to all profiles; `profiles` restricts the key to `profileIds`.'
        ),
    ] = 'full'
    profileIds: Annotated[
        list[str] | None,
        Field(
            description='PostZen profile ids. Required when `scope` is `profiles`, and forbidden when `scope` is `full`.'
        ),
    ] = None
    permission: Annotated[
        Literal['read-write', 'read'] | None,
        Field(description='`read` keys may only call `GET` endpoints.'),
    ] = 'read-write'


class ApiKeyCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    message: str
    apiKey: ApiKeyWithSecret


class AnalyticsErrorResponse(ErrorResponse):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: (
        Literal[
            'x',
            'instagram',
            'tiktok',
            'linkedin',
            'facebook',
            'youtube',
            'threads',
            'pinterest',
            'bluesky',
            'telegram',
        ]
        | None
    ) = None
    platformError: Annotated[
        str | None,
        Field(description='Original error detail returned by the social platform.'),
    ] = None


class AnalyticsListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    posts: Annotated[
        list[AnalyticsPost],
        Field(
            description="One entry per PostZen post, not per platform target. A post published to several platforms appears once, with one `platformAnalytics` entry per platform and `analytics` summed across them; `platform` is that post's only platform when it has one. Posts imported from a platform always appear on their own. `pagination.total` and `overview.totalPosts` count these grouped entries."
        ),
    ]
    pagination: Pagination
    overview: AnalyticsOverview
    truncated: Annotated[
        bool,
        Field(
            description='True when the requested window contained more posts than a single response can scan. `pagination.total` and `overview` then describe the most recent slice of the window rather than all of it; narrow `dateFrom`/`dateTo`, `accountId`, or `platform` to get exact totals.'
        ),
    ]


class ApiPostPlatformResult(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    accountId: ApiPostAccount
    status: Literal[
        'draft', 'scheduled', 'pending', 'publishing', 'published', 'failed', 'canceled'
    ]
    platformPostUrl: str | None = None
    error: str | None = None


class CreatePostTarget(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    platform: Literal[
        'twitter',
        'x',
        'instagram',
        'tiktok',
        'linkedin',
        'facebook',
        'youtube',
        'threads',
        'pinterest',
        'bluesky',
        'telegram',
    ]
    accountId: Annotated[
        str, Field(description='PostZen account id or provider account id.')
    ]
    customContent: Annotated[
        str | None, Field(description='Overrides shared `content` for this platform.')
    ] = None
    settings: Annotated[
        InstagramSettings
        | FacebookSettings
        | ThreadsSettings
        | TikTokSettings
        | LinkedInSettings
        | XSettings
        | YouTubeSettings
        | PinterestSettings
        | BlueskySettings
        | TelegramSettings
        | None,
        Field(
            description='Platform-specific publishing options. Unknown keys are ignored.'
        ),
    ] = None


class ApiPost(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    field_id: Annotated[str, Field(alias='_id')]
    title: str | None
    content: str
    status: str
    scheduledFor: datetime | None
    timezone: str
    platforms: list[ApiPostPlatformResult]


class CreatePostResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    post: ApiPost
    message: Literal[
        'Post published successfully',
        'Post scheduled successfully',
        'Draft created successfully',
    ]


class CreatePostReplayResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    existingPost: ApiPost
    message: Literal['Post already exists for this request id']


class PostsListResponse(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    posts: list[ApiPost]
    pagination: Pagination


class CreatePostRequest(BaseModel):
    model_config = ConfigDict(
        extra='ignore',
        populate_by_name=True,
    )
    title: Annotated[
        str | None,
        Field(
            description='Internal post title. YouTube uses this as the fallback video title when `settings.title` is omitted.'
        ),
    ] = None
    content: Annotated[
        str | None,
        Field(
            description='Shared post text. Platform-specific validation still applies.'
        ),
    ] = ''
    mediaItems: Annotated[
        list[PostMediaItem] | None,
        Field(
            description='Duplicate URLs are removed before the post is created.',
            max_length=10,
        ),
    ] = None
    platforms: list[CreatePostTarget] | None = None
    scheduledFor: Annotated[
        datetime | None,
        Field(
            description='ISO 8601 date for scheduled posts. Must be at least 60 seconds in the future.'
        ),
    ] = None
    publishNow: Annotated[
        bool | None, Field(description='Publish synchronously where possible.')
    ] = None
    isDraft: Annotated[
        bool | None,
        Field(description='Create a draft. `platforms` is optional for drafts.'),
    ] = None
    timezone: str | None = 'UTC'
    tags: list[str] | None = None
