"""API resources.

This file is regenerated by `python scripts/generate_resources.py`.
Manual resource modules in this package take precedence over generated modules.
"""

from ._generated.accounts import AccountsResource
from ._generated.connect import ConnectResource
from ._generated.posts import PostsResource
from ._generated.profiles import ProfilesResource
from .media import MediaResource

__all__ = [
    "ProfilesResource",
    "AccountsResource",
    "ConnectResource",
    "MediaResource",
    "PostsResource",
]
