#!/usr/bin/env python3
"""Generate endpoint existence tests from openapi.json."""

from __future__ import annotations

import json
import re
from pathlib import Path

TAG_TO_RESOURCE = {
    "Profiles": "profiles",
    "Accounts": "accounts",
    "Connect": "connect",
    "Media": "media",
    "Posts": "posts",
}
RESOURCE_ORDER = ["profiles", "accounts", "connect", "media", "posts"]


def camel_to_snake(name: str) -> str:
    name = name.replace("-", "_")
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", name)
    return name.lower()


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    spec = json.loads((root / "openapi.json").read_text())
    endpoints: dict[str, list[str]] = {name: [] for name in RESOURCE_ORDER}
    for path_item in spec.get("paths", {}).values():
        if not isinstance(path_item, dict):
            continue
        for http_method, operation in path_item.items():
            if http_method not in {"get", "post", "put", "patch", "delete"} or not isinstance(operation, dict):
                continue
            tag = operation.get("tags", [""])[0]
            resource = TAG_TO_RESOURCE.get(tag)
            if resource and operation.get("operationId"):
                endpoints[resource].append(camel_to_snake(operation["operationId"]))

    lines = [
        '"""Auto-generated endpoint surface tests.',
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Run `python scripts/generate_endpoint_tests.py` to regenerate.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "def test_all_spec_endpoints_are_available(client):",
        "    expected = {",
    ]
    for resource in RESOURCE_ORDER:
        lines.append(f'        "{resource}": [')
        for method in endpoints[resource]:
            lines.append(f'            "{method}",')
        lines.append("        ],")
    lines.extend(
        [
            "    }",
            "    for resource_name, methods in expected.items():",
            "        resource = getattr(client, resource_name)",
            "        for method in methods:",
            "            assert callable(getattr(resource, method))",
            "            assert callable(getattr(resource, f'a{method}'))",
        ]
    )
    (root / "tests" / "test_endpoints.py").write_text("\n".join(lines) + "\n")
    print("Generated tests/test_endpoints.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
