#!/usr/bin/env python3
"""Generate endpoint existence tests from openapi.json."""

from __future__ import annotations

import json
from pathlib import Path

from resource_map import camel_to_snake, operations, resource_order


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    spec = json.loads((root / "openapi.json").read_text())
    order = resource_order(spec)
    tag_to_resource = dict(order)
    endpoints = {key: [] for _, key in order}
    for _, _, _, operation in operations(spec):
        for tag in operation["tags"]:
            resource = tag_to_resource[tag]
            operation_id = operation["operationId"]
            endpoints[resource].append(camel_to_snake(operation_id))

    lines = [
        '"""Auto-generated endpoint surface tests.',
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Run `python scripts/generate_endpoint_tests.py` to regenerate.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "def test_all_spec_endpoints_are_available(client):",
        "    expected = {",
    ]
    for _, resource in order:
        lines.append(f'        "{resource}": [')
        for method in endpoints[resource]:
            lines.append(f'            "{method}",')
        lines.append("        ],")
    lines.extend(
        [
            "    }",
            "    for resource_name, methods in expected.items():",
            "        resource = getattr(client, resource_name)",
            "        for method in methods:",
            "            assert callable(getattr(resource, method))",
            "            assert callable(getattr(resource, f'a{method}'))",
        ]
    )
    (root / "tests" / "test_endpoints.py").write_text("\n".join(lines) + "\n")
    print("Generated tests/test_endpoints.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
