# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from postzen.models.account_profile_summary import AccountProfileSummary
from postzen.models.public_platform_output import PublicPlatformOutput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Account(BaseModel):
    """
    Account
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    platform: PublicPlatformOutput
    provider_account_id: StrictStr = Field(alias="providerAccountId")
    profile_id: AccountProfileSummary = Field(alias="profileId")
    username: StrictStr
    display_name: StrictStr = Field(alias="displayName")
    profile_url: Optional[StrictStr] = Field(default=None, alias="profileUrl")
    avatar_url: Optional[StrictStr] = Field(default=None, alias="avatarUrl")
    status: StrictStr
    is_active: StrictBool = Field(alias="isActive")
    connected_at: datetime = Field(alias="connectedAt")
    last_synced_at: Optional[datetime] = Field(default=None, alias="lastSyncedAt")
    __properties: ClassVar[List[str]] = ["_id", "platform", "providerAccountId", "profileId", "username", "displayName", "profileUrl", "avatarUrl", "status", "isActive", "connectedAt", "lastSyncedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['connected', 'needsReauth', 'disconnected', 'disabled']):
            raise ValueError("must be one of enum values ('connected', 'needsReauth', 'disconnected', 'disabled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Account from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of profile_id
        if self.profile_id:
            _dict['profileId'] = self.profile_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Account from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "platform": obj.get("platform"),
            "providerAccountId": obj.get("providerAccountId"),
            "profileId": AccountProfileSummary.from_dict(obj["profileId"]) if obj.get("profileId") is not None else None,
            "username": obj.get("username"),
            "displayName": obj.get("displayName"),
            "profileUrl": obj.get("profileUrl"),
            "avatarUrl": obj.get("avatarUrl"),
            "status": obj.get("status"),
            "isActive": obj.get("isActive"),
            "connectedAt": obj.get("connectedAt"),
            "lastSyncedAt": obj.get("lastSyncedAt")
        })
        return _obj


