# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from postzen.models.account import Account
from postzen.models.public_platform_output import PublicPlatformOutput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectCompleteResponse(BaseModel):
    """
    ConnectCompleteResponse
    """ # noqa: E501
    message: StrictStr
    platform: PublicPlatformOutput
    profile_id: StrictStr = Field(alias="profileId")
    status: StrictStr
    missing_scopes: Optional[List[StrictStr]] = Field(default=None, alias="missingScopes")
    connected_account_count: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="connectedAccountCount")
    accounts: Optional[List[Account]] = None
    __properties: ClassVar[List[str]] = ["message", "platform", "profileId", "status", "missingScopes", "connectedAccountCount", "accounts"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['connected', 'needsReauth']):
            raise ValueError("must be one of enum values ('connected', 'needsReauth')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectCompleteResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectCompleteResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "platform": obj.get("platform"),
            "profileId": obj.get("profileId"),
            "status": obj.get("status"),
            "missingScopes": obj.get("missingScopes"),
            "connectedAccountCount": obj.get("connectedAccountCount"),
            "accounts": [Account.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None
        })
        return _obj


