# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from postzen.models.create_post_target import CreatePostTarget
from postzen.models.post_media_item import PostMediaItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePostRequest(BaseModel):
    """
    Provide exactly one creation mode: `publishNow`, `scheduledFor`, or `isDraft`. `platforms` is required unless `isDraft` is true.
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="Internal post title. YouTube uses this as the fallback video title when `settings.title` is omitted.")
    content: Optional[StrictStr] = Field(default='', description="Shared post text. Platform-specific validation still applies.")
    media_items: Optional[Annotated[List[PostMediaItem], Field(max_length=10)]] = Field(default=None, description="Duplicate URLs are removed before the post is created.", alias="mediaItems")
    platforms: Optional[List[CreatePostTarget]] = None
    scheduled_for: Optional[datetime] = Field(default=None, description="ISO 8601 date for scheduled posts. Must be at least 60 seconds in the future.", alias="scheduledFor")
    publish_now: Optional[StrictBool] = Field(default=None, description="Publish synchronously where possible.", alias="publishNow")
    is_draft: Optional[StrictBool] = Field(default=None, description="Create a draft. `platforms` is optional for drafts.", alias="isDraft")
    timezone: Optional[StrictStr] = 'UTC'
    tags: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["title", "content", "mediaItems", "platforms", "scheduledFor", "publishNow", "isDraft", "timezone", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in media_items (list)
        _items = []
        if self.media_items:
            for _item_media_items in self.media_items:
                if _item_media_items:
                    _items.append(_item_media_items.to_dict())
            _dict['mediaItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in platforms (list)
        _items = []
        if self.platforms:
            for _item_platforms in self.platforms:
                if _item_platforms:
                    _items.append(_item_platforms.to_dict())
            _dict['platforms'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "content": obj.get("content") if obj.get("content") is not None else '',
            "mediaItems": [PostMediaItem.from_dict(_item) for _item in obj["mediaItems"]] if obj.get("mediaItems") is not None else None,
            "platforms": [CreatePostTarget.from_dict(_item) for _item in obj["platforms"]] if obj.get("platforms") is not None else None,
            "scheduledFor": obj.get("scheduledFor"),
            "publishNow": obj.get("publishNow"),
            "isDraft": obj.get("isDraft"),
            "timezone": obj.get("timezone") if obj.get("timezone") is not None else 'UTC',
            "tags": obj.get("tags")
        })
        return _obj


