# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from postzen.models.instagram_settings_user_tags_inner import InstagramSettingsUserTagsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstagramSettings(BaseModel):
    """
    InstagramSettings
    """ # noqa: E501
    post_type: Optional[StrictStr] = Field(default='feed', alias="postType")
    collaborators: Optional[List[StrictStr]] = None
    user_tags: Optional[List[InstagramSettingsUserTagsInner]] = Field(default=None, alias="userTags")
    first_comment: Optional[StrictStr] = Field(default=None, alias="firstComment")
    share_to_feed: Optional[StrictBool] = Field(default=None, alias="shareToFeed")
    __properties: ClassVar[List[str]] = ["postType", "collaborators", "userTags", "firstComment", "shareToFeed"]

    @field_validator('post_type')
    def post_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['feed', 'story', 'reel', 'carousel']):
            raise ValueError("must be one of enum values ('feed', 'story', 'reel', 'carousel')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstagramSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in user_tags (list)
        _items = []
        if self.user_tags:
            for _item_user_tags in self.user_tags:
                if _item_user_tags:
                    _items.append(_item_user_tags.to_dict())
            _dict['userTags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstagramSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "postType": obj.get("postType") if obj.get("postType") is not None else 'feed',
            "collaborators": obj.get("collaborators"),
            "userTags": [InstagramSettingsUserTagsInner.from_dict(_item) for _item in obj["userTags"]] if obj.get("userTags") is not None else None,
            "firstComment": obj.get("firstComment"),
            "shareToFeed": obj.get("shareToFeed")
        })
        return _obj


