# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from postzen.models.facebook_settings import FacebookSettings
from postzen.models.instagram_settings import InstagramSettings
from postzen.models.linked_in_settings import LinkedInSettings
from postzen.models.pinterest_settings import PinterestSettings
from postzen.models.threads_settings import ThreadsSettings
from postzen.models.tik_tok_settings import TikTokSettings
from postzen.models.x_settings import XSettings
from postzen.models.you_tube_settings import YouTubeSettings
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

POSTPLATFORMSETTINGS_ONE_OF_SCHEMAS = ["FacebookSettings", "InstagramSettings", "LinkedInSettings", "PinterestSettings", "ThreadsSettings", "TikTokSettings", "XSettings", "YouTubeSettings"]

class PostPlatformSettings(BaseModel):
    """
    Platform-specific publishing options. Unknown keys are ignored.
    """
    # data type: InstagramSettings
    oneof_schema_1_validator: Optional[InstagramSettings] = None
    # data type: FacebookSettings
    oneof_schema_2_validator: Optional[FacebookSettings] = None
    # data type: ThreadsSettings
    oneof_schema_3_validator: Optional[ThreadsSettings] = None
    # data type: TikTokSettings
    oneof_schema_4_validator: Optional[TikTokSettings] = None
    # data type: LinkedInSettings
    oneof_schema_5_validator: Optional[LinkedInSettings] = None
    # data type: XSettings
    oneof_schema_6_validator: Optional[XSettings] = None
    # data type: YouTubeSettings
    oneof_schema_7_validator: Optional[YouTubeSettings] = None
    # data type: PinterestSettings
    oneof_schema_8_validator: Optional[PinterestSettings] = None
    actual_instance: Optional[Union[FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings]] = None
    one_of_schemas: Set[str] = { "FacebookSettings", "InstagramSettings", "LinkedInSettings", "PinterestSettings", "ThreadsSettings", "TikTokSettings", "XSettings", "YouTubeSettings" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PostPlatformSettings.model_construct()
        error_messages = []
        match = 0
        # validate data type: InstagramSettings
        if not isinstance(v, InstagramSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InstagramSettings`")
        else:
            match += 1
        # validate data type: FacebookSettings
        if not isinstance(v, FacebookSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FacebookSettings`")
        else:
            match += 1
        # validate data type: ThreadsSettings
        if not isinstance(v, ThreadsSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ThreadsSettings`")
        else:
            match += 1
        # validate data type: TikTokSettings
        if not isinstance(v, TikTokSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TikTokSettings`")
        else:
            match += 1
        # validate data type: LinkedInSettings
        if not isinstance(v, LinkedInSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LinkedInSettings`")
        else:
            match += 1
        # validate data type: XSettings
        if not isinstance(v, XSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `XSettings`")
        else:
            match += 1
        # validate data type: YouTubeSettings
        if not isinstance(v, YouTubeSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `YouTubeSettings`")
        else:
            match += 1
        # validate data type: PinterestSettings
        if not isinstance(v, PinterestSettings):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PinterestSettings`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PostPlatformSettings with oneOf schemas: FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PostPlatformSettings with oneOf schemas: FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into InstagramSettings
        try:
            instance.actual_instance = InstagramSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FacebookSettings
        try:
            instance.actual_instance = FacebookSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ThreadsSettings
        try:
            instance.actual_instance = ThreadsSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TikTokSettings
        try:
            instance.actual_instance = TikTokSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LinkedInSettings
        try:
            instance.actual_instance = LinkedInSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into XSettings
        try:
            instance.actual_instance = XSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into YouTubeSettings
        try:
            instance.actual_instance = YouTubeSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PinterestSettings
        try:
            instance.actual_instance = PinterestSettings.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PostPlatformSettings with oneOf schemas: FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PostPlatformSettings with oneOf schemas: FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FacebookSettings, InstagramSettings, LinkedInSettings, PinterestSettings, ThreadsSettings, TikTokSettings, XSettings, YouTubeSettings]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


