# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PublicPlatformInput(str, Enum):
    """
    PublicPlatformInput
    """

    """
    allowed enum values
    """
    TWITTER = 'twitter'
    X = 'x'
    INSTAGRAM = 'instagram'
    TIKTOK = 'tiktok'
    LINKEDIN = 'linkedin'
    FACEBOOK = 'facebook'
    YOUTUBE = 'youtube'
    THREADS = 'threads'
    PINTEREST = 'pinterest'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PublicPlatformInput from a JSON string"""
        return cls(json.loads(json_str))


