# coding: utf-8

"""
    PostZen Public API

    The PostZen Public API lets server-side integrations manage profiles, connected social accounts, OAuth connection flows, media uploads, and post creation.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TikTokSettings(BaseModel):
    """
    TikTokSettings
    """ # noqa: E501
    privacy_level: Optional[StrictStr] = Field(default=None, alias="privacyLevel")
    allow_comments: Optional[StrictBool] = Field(default=None, alias="allowComments")
    allow_duet: Optional[StrictBool] = Field(default=None, alias="allowDuet")
    allow_stitch: Optional[StrictBool] = Field(default=None, alias="allowStitch")
    disable_comment: Optional[StrictBool] = Field(default=None, alias="disableComment")
    disable_duet: Optional[StrictBool] = Field(default=None, alias="disableDuet")
    disable_stitch: Optional[StrictBool] = Field(default=None, alias="disableStitch")
    video_cover_timestamp_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="videoCoverTimestampMs")
    upload_as_draft: Optional[StrictBool] = Field(default=None, alias="uploadAsDraft")
    brand_content_toggle: Optional[StrictBool] = Field(default=None, alias="brandContentToggle")
    brand_organic_toggle: Optional[StrictBool] = Field(default=None, alias="brandOrganicToggle")
    __properties: ClassVar[List[str]] = ["privacyLevel", "allowComments", "allowDuet", "allowStitch", "disableComment", "disableDuet", "disableStitch", "videoCoverTimestampMs", "uploadAsDraft", "brandContentToggle", "brandOrganicToggle"]

    @field_validator('privacy_level')
    def privacy_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['publicToEveryone', 'mutualFollowFriends', 'followerOfCreator', 'selfOnly']):
            raise ValueError("must be one of enum values ('publicToEveryone', 'mutualFollowFriends', 'followerOfCreator', 'selfOnly')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TikTokSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TikTokSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "privacyLevel": obj.get("privacyLevel"),
            "allowComments": obj.get("allowComments"),
            "allowDuet": obj.get("allowDuet"),
            "allowStitch": obj.get("allowStitch"),
            "disableComment": obj.get("disableComment"),
            "disableDuet": obj.get("disableDuet"),
            "disableStitch": obj.get("disableStitch"),
            "videoCoverTimestampMs": obj.get("videoCoverTimestampMs"),
            "uploadAsDraft": obj.get("uploadAsDraft"),
            "brandContentToggle": obj.get("brandContentToggle"),
            "brandOrganicToggle": obj.get("brandOrganicToggle")
        })
        return _obj


