"""
Auto-generated analytics resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    BestTimeResponse,
    DailyMetricsResponse,
    FollowerStatsResponse,
    PostTimelineResponse,
    SyncExternalPostsResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class AnalyticsResource(BaseResource[Any]):
    """Read post, engagement, follower, and posting-time analytics, and synchronize external posts."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def get_analytics(self, *, post_id: str | None = None, platform: Any | None = 'all', profile_id: str | None = 'all', account_id: str | None = None, source: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, limit: int | None = 50, page: int | None = 1, sort_by: str | None = 'date', order: str | None = 'desc') -> dict[str, Any]:
        """Get post analytics."""
        params = self._build_params(
            post_id=post_id,
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            source=source,
            from_date=from_date,
            to_date=to_date,
            limit=limit,
            page=page,
            sort_by=sort_by,
            order=order,
        )
        data = self._client._get('/v1/analytics', params=params)
        return data

    async def aget_analytics(self, *, post_id: str | None = None, platform: Any | None = 'all', profile_id: str | None = 'all', account_id: str | None = None, source: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, limit: int | None = 50, page: int | None = 1, sort_by: str | None = 'date', order: str | None = 'desc') -> dict[str, Any]:
        """Get post analytics (async)."""
        params = self._build_params(
            post_id=post_id,
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            source=source,
            from_date=from_date,
            to_date=to_date,
            limit=limit,
            page=page,
            sort_by=sort_by,
            order=order,
        )
        data = await self._client._aget('/v1/analytics', params=params)
        return data

    def get_post_timeline(self, *, post_id: str, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None) -> PostTimelineResponse:
        """Get a post analytics timeline."""
        params = self._build_params(
            post_id=post_id,
            from_date=from_date,
            to_date=to_date,
        )
        data = self._client._get('/v1/analytics/post-timeline', params=params)
        return PostTimelineResponse.model_validate(data)

    async def aget_post_timeline(self, *, post_id: str, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None) -> PostTimelineResponse:
        """Get a post analytics timeline (async)."""
        params = self._build_params(
            post_id=post_id,
            from_date=from_date,
            to_date=to_date,
        )
        data = await self._client._aget('/v1/analytics/post-timeline', params=params)
        return PostTimelineResponse.model_validate(data)

    def get_daily_metrics(self, *, platform: str | None = None, profile_id: str | None = None, account_id: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, source: str | None = None, attribution: str | None = 'publish') -> DailyMetricsResponse:
        """Get daily analytics metrics."""
        params = self._build_params(
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            from_date=from_date,
            to_date=to_date,
            source=source,
            attribution=attribution,
        )
        data = self._client._get('/v1/analytics/daily-metrics', params=params)
        return DailyMetricsResponse.model_validate(data)

    async def aget_daily_metrics(self, *, platform: str | None = None, profile_id: str | None = None, account_id: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, source: str | None = None, attribution: str | None = 'publish') -> DailyMetricsResponse:
        """Get daily analytics metrics (async)."""
        params = self._build_params(
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            from_date=from_date,
            to_date=to_date,
            source=source,
            attribution=attribution,
        )
        data = await self._client._aget('/v1/analytics/daily-metrics', params=params)
        return DailyMetricsResponse.model_validate(data)

    def get_best_time_to_post(self, *, platform: str | None = None, profile_id: str | None = None, account_id: str | None = None, source: str | None = None) -> BestTimeResponse:
        """Get the best times to post."""
        params = self._build_params(
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            source=source,
        )
        data = self._client._get('/v1/analytics/best-time', params=params)
        return BestTimeResponse.model_validate(data)

    async def aget_best_time_to_post(self, *, platform: str | None = None, profile_id: str | None = None, account_id: str | None = None, source: str | None = None) -> BestTimeResponse:
        """Get the best times to post (async)."""
        params = self._build_params(
            platform=platform,
            profile_id=profile_id,
            account_id=account_id,
            source=source,
        )
        data = await self._client._aget('/v1/analytics/best-time', params=params)
        return BestTimeResponse.model_validate(data)

    def get_follower_stats(self, *, account_ids: str | None = None, profile_id: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, granularity: str | None = 'daily') -> FollowerStatsResponse:
        """Get follower statistics."""
        params = self._build_params(
            account_ids=account_ids,
            profile_id=profile_id,
            from_date=from_date,
            to_date=to_date,
            granularity=granularity,
        )
        data = self._client._get('/v1/accounts/follower-stats', params=params)
        return FollowerStatsResponse.model_validate(data)

    async def aget_follower_stats(self, *, account_ids: str | None = None, profile_id: str | None = None, from_date: dict[str, Any] | None = None, to_date: dict[str, Any] | None = None, granularity: str | None = 'daily') -> FollowerStatsResponse:
        """Get follower statistics (async)."""
        params = self._build_params(
            account_ids=account_ids,
            profile_id=profile_id,
            from_date=from_date,
            to_date=to_date,
            granularity=granularity,
        )
        data = await self._client._aget('/v1/accounts/follower-stats', params=params)
        return FollowerStatsResponse.model_validate(data)

    def sync_external_posts(self, *, account_id: str, url: str | None = None, post_id: str | None = None) -> SyncExternalPostsResponse:
        """Synchronize external posts."""
        payload = self._build_payload(
            account_id=account_id,
            url=url,
            post_id=post_id,
        )
        data = self._client._post('/v1/posts/sync-external', data=payload)
        return SyncExternalPostsResponse.model_validate(data)

    async def async_external_posts(self, *, account_id: str, url: str | None = None, post_id: str | None = None) -> SyncExternalPostsResponse:
        """Synchronize external posts (async)."""
        payload = self._build_payload(
            account_id=account_id,
            url=url,
            post_id=post_id,
        )
        data = await self._client._apost('/v1/posts/sync-external', data=payload)
        return SyncExternalPostsResponse.model_validate(data)
