"""
Auto-generated api_keys resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    ApiKeyCreateResponse,
    ApiKeysListResponse,
    MessageResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class ApiKeysResource(BaseResource[Any]):
    """Manage PostZen API keys programmatically."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_api_keys(self) -> ApiKeysListResponse:
        """List API keys."""
        data = self._client._get('/v1/api-keys')
        return ApiKeysListResponse.model_validate(data)

    async def alist_api_keys(self) -> ApiKeysListResponse:
        """List API keys (async)."""
        data = await self._client._aget('/v1/api-keys')
        return ApiKeysListResponse.model_validate(data)

    def create_api_key(self, *, name: str, scope: str | None = 'full', profile_ids: list[str] | None = None, permission: str | None = 'read-write') -> ApiKeyCreateResponse:
        """Create an API key."""
        payload = self._build_payload(
            name=name,
            scope=scope,
            profile_ids=profile_ids,
            permission=permission,
        )
        data = self._client._post('/v1/api-keys', data=payload)
        return ApiKeyCreateResponse.model_validate(data)

    async def acreate_api_key(self, *, name: str, scope: str | None = 'full', profile_ids: list[str] | None = None, permission: str | None = 'read-write') -> ApiKeyCreateResponse:
        """Create an API key (async)."""
        payload = self._build_payload(
            name=name,
            scope=scope,
            profile_ids=profile_ids,
            permission=permission,
        )
        data = await self._client._apost('/v1/api-keys', data=payload)
        return ApiKeyCreateResponse.model_validate(data)

    def delete_api_key(self, key_id: str) -> MessageResponse:
        """Delete an API key."""
        data = self._client._delete(f"/v1/api-keys/{key_id}")
        return MessageResponse.model_validate(data)

    async def adelete_api_key(self, key_id: str) -> MessageResponse:
        """Delete an API key (async)."""
        data = await self._client._adelete(f"/v1/api-keys/{key_id}")
        return MessageResponse.model_validate(data)
