"""
Auto-generated comment_automations resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    CommentAutomationDetailResponse,
    CommentAutomationListResponse,
    CommentAutomationLogsResponse,
    CommentAutomationResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class CommentAutomationsResource(BaseResource[Any]):
    """Instagram comment and story reply automations with private replies and delivery logs."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_comment_automations(self, *, profile_id: str | None = None, account_id: str | None = None) -> CommentAutomationListResponse:
        """List comment automations."""
        params = self._build_params(
            profile_id=profile_id,
            account_id=account_id,
        )
        data = self._client._get('/v1/comment-automations', params=params)
        return CommentAutomationListResponse.model_validate(data)

    async def alist_comment_automations(self, *, profile_id: str | None = None, account_id: str | None = None) -> CommentAutomationListResponse:
        """List comment automations (async)."""
        params = self._build_params(
            profile_id=profile_id,
            account_id=account_id,
        )
        data = await self._client._aget('/v1/comment-automations', params=params)
        return CommentAutomationListResponse.model_validate(data)

    def create_comment_automation(self, *, account_id: str, name: str, profile_id: str | None = None, trigger: str | None = 'comment', platform_post_id: str | None = None, post_id: str | None = None, post_title: str | None = None, keywords: list[str] | None = None, match_mode: str | None = 'contains', exclude_keywords: list[str] | None = None, typo_tolerance: bool | None = False, dm_message: str | None = None, dm_message_variations: list[str] | None = None, buttons: list[dict[str, Any]] | None = None, template: dict[str, Any] | None = None, comment_reply: str | None = None, comment_reply_variations: list[str] | None = None, dm_delay_seconds: int | None = 0, comment_reply_delay_seconds: int | None = 0, is_active: bool | None = True, link_tracking: bool | None = False, audience: dict[str, Any] | None = None, opening_dm: Any | None = None, follow_gate: dict[str, Any] | None = None) -> CommentAutomationResponse:
        """Create a comment automation."""
        if keywords is None:
            keywords = []
        if exclude_keywords is None:
            exclude_keywords = []
        if dm_message_variations is None:
            dm_message_variations = []
        if buttons is None:
            buttons = []
        if comment_reply_variations is None:
            comment_reply_variations = []
        payload = self._build_payload(
            account_id=account_id,
            profile_id=profile_id,
            name=name,
            trigger=trigger,
            platform_post_id=platform_post_id,
            post_id=post_id,
            post_title=post_title,
            keywords=keywords,
            match_mode=match_mode,
            exclude_keywords=exclude_keywords,
            typo_tolerance=typo_tolerance,
            dm_message=dm_message,
            dm_message_variations=dm_message_variations,
            buttons=buttons,
            template=template,
            comment_reply=comment_reply,
            comment_reply_variations=comment_reply_variations,
            dm_delay_seconds=dm_delay_seconds,
            comment_reply_delay_seconds=comment_reply_delay_seconds,
            is_active=is_active,
            link_tracking=link_tracking,
            audience=audience,
            opening_dm=opening_dm,
            follow_gate=follow_gate,
        )
        data = self._client._post('/v1/comment-automations', data=payload)
        return CommentAutomationResponse.model_validate(data)

    async def acreate_comment_automation(self, *, account_id: str, name: str, profile_id: str | None = None, trigger: str | None = 'comment', platform_post_id: str | None = None, post_id: str | None = None, post_title: str | None = None, keywords: list[str] | None = None, match_mode: str | None = 'contains', exclude_keywords: list[str] | None = None, typo_tolerance: bool | None = False, dm_message: str | None = None, dm_message_variations: list[str] | None = None, buttons: list[dict[str, Any]] | None = None, template: dict[str, Any] | None = None, comment_reply: str | None = None, comment_reply_variations: list[str] | None = None, dm_delay_seconds: int | None = 0, comment_reply_delay_seconds: int | None = 0, is_active: bool | None = True, link_tracking: bool | None = False, audience: dict[str, Any] | None = None, opening_dm: Any | None = None, follow_gate: dict[str, Any] | None = None) -> CommentAutomationResponse:
        """Create a comment automation (async)."""
        if keywords is None:
            keywords = []
        if exclude_keywords is None:
            exclude_keywords = []
        if dm_message_variations is None:
            dm_message_variations = []
        if buttons is None:
            buttons = []
        if comment_reply_variations is None:
            comment_reply_variations = []
        payload = self._build_payload(
            account_id=account_id,
            profile_id=profile_id,
            name=name,
            trigger=trigger,
            platform_post_id=platform_post_id,
            post_id=post_id,
            post_title=post_title,
            keywords=keywords,
            match_mode=match_mode,
            exclude_keywords=exclude_keywords,
            typo_tolerance=typo_tolerance,
            dm_message=dm_message,
            dm_message_variations=dm_message_variations,
            buttons=buttons,
            template=template,
            comment_reply=comment_reply,
            comment_reply_variations=comment_reply_variations,
            dm_delay_seconds=dm_delay_seconds,
            comment_reply_delay_seconds=comment_reply_delay_seconds,
            is_active=is_active,
            link_tracking=link_tracking,
            audience=audience,
            opening_dm=opening_dm,
            follow_gate=follow_gate,
        )
        data = await self._client._apost('/v1/comment-automations', data=payload)
        return CommentAutomationResponse.model_validate(data)

    def get_comment_automation(self, automation_id: str) -> CommentAutomationDetailResponse:
        """Get a comment automation."""
        data = self._client._get(f"/v1/comment-automations/{automation_id}")
        return CommentAutomationDetailResponse.model_validate(data)

    async def aget_comment_automation(self, automation_id: str) -> CommentAutomationDetailResponse:
        """Get a comment automation (async)."""
        data = await self._client._aget(f"/v1/comment-automations/{automation_id}")
        return CommentAutomationDetailResponse.model_validate(data)

    def update_comment_automation(self, automation_id: str, *, profile_id: str | None = None, name: str | None = None, trigger: str | None = None, platform_post_id: str | None = None, post_id: str | None = None, post_title: str | None = None, keywords: list[str] | None = None, match_mode: str | None = None, exclude_keywords: list[str] | None = None, typo_tolerance: bool | None = None, dm_message: str | None = None, dm_message_variations: list[str] | None = None, buttons: list[dict[str, Any]] | None = None, template: Any | None = None, comment_reply: str | None = None, comment_reply_variations: list[str] | None = None, dm_delay_seconds: int | None = None, comment_reply_delay_seconds: int | None = None, is_active: bool | None = None, link_tracking: bool | None = None, audience: Any | None = None, opening_dm: Any | None = None, follow_gate: Any | None = None) -> CommentAutomationResponse:
        """Update a comment automation."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            trigger=trigger,
            platform_post_id=platform_post_id,
            post_id=post_id,
            post_title=post_title,
            keywords=keywords,
            match_mode=match_mode,
            exclude_keywords=exclude_keywords,
            typo_tolerance=typo_tolerance,
            dm_message=dm_message,
            dm_message_variations=dm_message_variations,
            buttons=buttons,
            template=template,
            comment_reply=comment_reply,
            comment_reply_variations=comment_reply_variations,
            dm_delay_seconds=dm_delay_seconds,
            comment_reply_delay_seconds=comment_reply_delay_seconds,
            is_active=is_active,
            link_tracking=link_tracking,
            audience=audience,
            opening_dm=opening_dm,
            follow_gate=follow_gate,
        )
        data = self._client._patch(f"/v1/comment-automations/{automation_id}", data=payload)
        return CommentAutomationResponse.model_validate(data)

    async def aupdate_comment_automation(self, automation_id: str, *, profile_id: str | None = None, name: str | None = None, trigger: str | None = None, platform_post_id: str | None = None, post_id: str | None = None, post_title: str | None = None, keywords: list[str] | None = None, match_mode: str | None = None, exclude_keywords: list[str] | None = None, typo_tolerance: bool | None = None, dm_message: str | None = None, dm_message_variations: list[str] | None = None, buttons: list[dict[str, Any]] | None = None, template: Any | None = None, comment_reply: str | None = None, comment_reply_variations: list[str] | None = None, dm_delay_seconds: int | None = None, comment_reply_delay_seconds: int | None = None, is_active: bool | None = None, link_tracking: bool | None = None, audience: Any | None = None, opening_dm: Any | None = None, follow_gate: Any | None = None) -> CommentAutomationResponse:
        """Update a comment automation (async)."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            trigger=trigger,
            platform_post_id=platform_post_id,
            post_id=post_id,
            post_title=post_title,
            keywords=keywords,
            match_mode=match_mode,
            exclude_keywords=exclude_keywords,
            typo_tolerance=typo_tolerance,
            dm_message=dm_message,
            dm_message_variations=dm_message_variations,
            buttons=buttons,
            template=template,
            comment_reply=comment_reply,
            comment_reply_variations=comment_reply_variations,
            dm_delay_seconds=dm_delay_seconds,
            comment_reply_delay_seconds=comment_reply_delay_seconds,
            is_active=is_active,
            link_tracking=link_tracking,
            audience=audience,
            opening_dm=opening_dm,
            follow_gate=follow_gate,
        )
        data = await self._client._apatch(f"/v1/comment-automations/{automation_id}", data=payload)
        return CommentAutomationResponse.model_validate(data)

    def delete_comment_automation(self, automation_id: str) -> dict[str, Any]:
        """Delete a comment automation."""
        data = self._client._delete(f"/v1/comment-automations/{automation_id}")
        return data

    async def adelete_comment_automation(self, automation_id: str) -> dict[str, Any]:
        """Delete a comment automation (async)."""
        data = await self._client._adelete(f"/v1/comment-automations/{automation_id}")
        return data

    def list_comment_automation_logs(self, automation_id: str, *, status: str | None = None, limit: int | None = 50, skip: int | None = 0) -> CommentAutomationLogsResponse:
        """List comment automation logs."""
        params = self._build_params(
            status=status,
            limit=limit,
            skip=skip,
        )
        data = self._client._get(f"/v1/comment-automations/{automation_id}/logs", params=params)
        return CommentAutomationLogsResponse.model_validate(data)

    async def alist_comment_automation_logs(self, automation_id: str, *, status: str | None = None, limit: int | None = 50, skip: int | None = 0) -> CommentAutomationLogsResponse:
        """List comment automation logs (async)."""
        params = self._build_params(
            status=status,
            limit=limit,
            skip=skip,
        )
        data = await self._client._aget(f"/v1/comment-automations/{automation_id}/logs", params=params)
        return CommentAutomationLogsResponse.model_validate(data)
