"""
Auto-generated connect resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    ConnectCompleteResponse,
    ConnectStartResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class ConnectResource(BaseResource[Any]):
    """Create and complete OAuth connection flows."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def create_connect_url(self, platform: str, *, profile_id: str, redirect_url: str | None = None) -> ConnectStartResponse:
        """Create an OAuth connect URL."""
        params = self._build_params(
            profile_id=profile_id,
            redirect_url=redirect_url,
        )
        data = self._client._get(f"/v1/connect/{platform}", params=params)
        return ConnectStartResponse.model_validate(data)

    async def acreate_connect_url(self, platform: str, *, profile_id: str, redirect_url: str | None = None) -> ConnectStartResponse:
        """Create an OAuth connect URL (async)."""
        params = self._build_params(
            profile_id=profile_id,
            redirect_url=redirect_url,
        )
        data = await self._client._aget(f"/v1/connect/{platform}", params=params)
        return ConnectStartResponse.model_validate(data)

    def complete_connect(self, platform: str, *, code: str, state: str, profile_id: str) -> ConnectCompleteResponse:
        """Complete an OAuth connection."""
        payload = self._build_payload(
            code=code,
            state=state,
            profile_id=profile_id,
        )
        data = self._client._post(f"/v1/connect/{platform}", data=payload)
        return ConnectCompleteResponse.model_validate(data)

    async def acomplete_connect(self, platform: str, *, code: str, state: str, profile_id: str) -> ConnectCompleteResponse:
        """Complete an OAuth connection (async)."""
        payload = self._build_payload(
            code=code,
            state=state,
            profile_id=profile_id,
        )
        data = await self._client._apost(f"/v1/connect/{platform}", data=payload)
        return ConnectCompleteResponse.model_validate(data)
