"""
Auto-generated contacts resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    ContactBulkCreateResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class ContactsResource(BaseResource[Any]):
    """Profile-owned people from the API, inbox, and comment automations."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_contacts(self, *, profile_id: str | None = None, account_id: str | None = None, search: str | None = None, tag: str | None = None, tags: str | None = None, platform: str | None = None, is_subscribed: str | None = None, limit: int | None = 50, skip: int | None = 0) -> dict[str, Any]:
        """List contacts."""
        params = self._build_params(
            profile_id=profile_id,
            account_id=account_id,
            search=search,
            tag=tag,
            tags=tags,
            platform=platform,
            is_subscribed=is_subscribed,
            limit=limit,
            skip=skip,
        )
        data = self._client._get('/v1/contacts', params=params)
        return data

    async def alist_contacts(self, *, profile_id: str | None = None, account_id: str | None = None, search: str | None = None, tag: str | None = None, tags: str | None = None, platform: str | None = None, is_subscribed: str | None = None, limit: int | None = 50, skip: int | None = 0) -> dict[str, Any]:
        """List contacts (async)."""
        params = self._build_params(
            profile_id=profile_id,
            account_id=account_id,
            search=search,
            tag=tag,
            tags=tags,
            platform=platform,
            is_subscribed=is_subscribed,
            limit=limit,
            skip=skip,
        )
        data = await self._client._aget('/v1/contacts', params=params)
        return data

    def create_contact(self, *, profile_id: str, name: str, email: str | None = None, company: str | None = None, tags: list[str] | None = None, is_subscribed: bool | None = True, notes: str | None = None, custom_fields: dict[str, Any] | None = None, account_id: str | None = None, platform_identifier: str | None = None, display_identifier: str | None = None, platform: str | None = None) -> dict[str, Any]:
        """Create a contact."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            email=email,
            company=company,
            tags=tags,
            is_subscribed=is_subscribed,
            notes=notes,
            custom_fields=custom_fields,
            account_id=account_id,
            platform_identifier=platform_identifier,
            display_identifier=display_identifier,
            platform=platform,
        )
        data = self._client._post('/v1/contacts', data=payload)
        return data

    async def acreate_contact(self, *, profile_id: str, name: str, email: str | None = None, company: str | None = None, tags: list[str] | None = None, is_subscribed: bool | None = True, notes: str | None = None, custom_fields: dict[str, Any] | None = None, account_id: str | None = None, platform_identifier: str | None = None, display_identifier: str | None = None, platform: str | None = None) -> dict[str, Any]:
        """Create a contact (async)."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            email=email,
            company=company,
            tags=tags,
            is_subscribed=is_subscribed,
            notes=notes,
            custom_fields=custom_fields,
            account_id=account_id,
            platform_identifier=platform_identifier,
            display_identifier=display_identifier,
            platform=platform,
        )
        data = await self._client._apost('/v1/contacts', data=payload)
        return data

    def bulk_create_contacts(self, *, profile_id: str, contacts: list[dict[str, Any]], account_id: str | None = None, platform: str | None = None) -> ContactBulkCreateResponse:
        """Bulk create contacts."""
        payload = self._build_payload(
            profile_id=profile_id,
            account_id=account_id,
            platform=platform,
            contacts=contacts,
        )
        data = self._client._post('/v1/contacts/bulk', data=payload)
        return ContactBulkCreateResponse.model_validate(data)

    async def abulk_create_contacts(self, *, profile_id: str, contacts: list[dict[str, Any]], account_id: str | None = None, platform: str | None = None) -> ContactBulkCreateResponse:
        """Bulk create contacts (async)."""
        payload = self._build_payload(
            profile_id=profile_id,
            account_id=account_id,
            platform=platform,
            contacts=contacts,
        )
        data = await self._client._apost('/v1/contacts/bulk', data=payload)
        return ContactBulkCreateResponse.model_validate(data)

    def get_contact(self, contact_id: str) -> dict[str, Any]:
        """Get a contact."""
        data = self._client._get(f"/v1/contacts/{contact_id}")
        return data

    async def aget_contact(self, contact_id: str) -> dict[str, Any]:
        """Get a contact (async)."""
        data = await self._client._aget(f"/v1/contacts/{contact_id}")
        return data

    def update_contact(self, contact_id: str, *, name: str | None = None, email: str | None = None, company: str | None = None, avatar_url: str | None = None, tags: list[str] | None = None, is_subscribed: bool | None = None, is_blocked: bool | None = None, notes: str | None = None, custom_fields: dict[str, Any] | None = None) -> dict[str, Any]:
        """Update a contact."""
        payload = self._build_payload(
            name=name,
            email=email,
            company=company,
            avatar_url=avatar_url,
            tags=tags,
            is_subscribed=is_subscribed,
            is_blocked=is_blocked,
            notes=notes,
            custom_fields=custom_fields,
        )
        data = self._client._patch(f"/v1/contacts/{contact_id}", data=payload)
        return data

    async def aupdate_contact(self, contact_id: str, *, name: str | None = None, email: str | None = None, company: str | None = None, avatar_url: str | None = None, tags: list[str] | None = None, is_subscribed: bool | None = None, is_blocked: bool | None = None, notes: str | None = None, custom_fields: dict[str, Any] | None = None) -> dict[str, Any]:
        """Update a contact (async)."""
        payload = self._build_payload(
            name=name,
            email=email,
            company=company,
            avatar_url=avatar_url,
            tags=tags,
            is_subscribed=is_subscribed,
            is_blocked=is_blocked,
            notes=notes,
            custom_fields=custom_fields,
        )
        data = await self._client._apatch(f"/v1/contacts/{contact_id}", data=payload)
        return data

    def delete_contact(self, contact_id: str) -> dict[str, Any]:
        """Delete a contact."""
        data = self._client._delete(f"/v1/contacts/{contact_id}")
        return data

    async def adelete_contact(self, contact_id: str) -> dict[str, Any]:
        """Delete a contact (async)."""
        data = await self._client._adelete(f"/v1/contacts/{contact_id}")
        return data

    def get_contact_channels(self, contact_id: str) -> dict[str, Any]:
        """Get contact channels."""
        data = self._client._get(f"/v1/contacts/{contact_id}/channels")
        return data

    async def aget_contact_channels(self, contact_id: str) -> dict[str, Any]:
        """Get contact channels (async)."""
        data = await self._client._aget(f"/v1/contacts/{contact_id}/channels")
        return data
