"""
Auto-generated inbox resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    InboxActionResponse,
    InboxCommentsResponse,
    InboxConversationReadResponse,
    InboxConversationResponse,
    InboxConversationSearchResponse,
    InboxConversationUpdateResponse,
    InboxConversationsResponse,
    InboxHideResponse,
    InboxMessageSendResponse,
    InboxMessagesResponse,
    InboxReplyResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class InboxResource(BaseResource[Any]):
    """Read and moderate comments on Instagram, Facebook, and Threads posts."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_inbox_post_comments(self, post_id: str, *, account_id: str, limit: int | None = 25, cursor: str | None = None, comment_id: str | None = None) -> InboxCommentsResponse:
        """List comments on a post."""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            comment_id=comment_id,
        )
        data = self._client._get(f"/v1/inbox/comments/{post_id}", params=params)
        return InboxCommentsResponse.model_validate(data)

    async def alist_inbox_post_comments(self, post_id: str, *, account_id: str, limit: int | None = 25, cursor: str | None = None, comment_id: str | None = None) -> InboxCommentsResponse:
        """List comments on a post (async)."""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            comment_id=comment_id,
        )
        data = await self._client._aget(f"/v1/inbox/comments/{post_id}", params=params)
        return InboxCommentsResponse.model_validate(data)

    def reply_to_inbox_post(self, post_id: str, *, account_id: str, message: str, comment_id: str | None = None, attachment_url: str | None = None) -> InboxReplyResponse:
        """Comment on a post or reply to a comment."""
        payload = self._build_payload(
            account_id=account_id,
            message=message,
            comment_id=comment_id,
            attachment_url=attachment_url,
        )
        data = self._client._post(f"/v1/inbox/comments/{post_id}", data=payload)
        return InboxReplyResponse.model_validate(data)

    async def areply_to_inbox_post(self, post_id: str, *, account_id: str, message: str, comment_id: str | None = None, attachment_url: str | None = None) -> InboxReplyResponse:
        """Comment on a post or reply to a comment (async)."""
        payload = self._build_payload(
            account_id=account_id,
            message=message,
            comment_id=comment_id,
            attachment_url=attachment_url,
        )
        data = await self._client._apost(f"/v1/inbox/comments/{post_id}", data=payload)
        return InboxReplyResponse.model_validate(data)

    def delete_inbox_comment(self, post_id: str, *, account_id: str, comment_id: str) -> InboxActionResponse:
        """Delete a comment."""
        params = self._build_params(
            account_id=account_id,
            comment_id=comment_id,
        )
        data = self._client._delete(f"/v1/inbox/comments/{post_id}", params=params)
        return InboxActionResponse.model_validate(data)

    async def adelete_inbox_comment(self, post_id: str, *, account_id: str, comment_id: str) -> InboxActionResponse:
        """Delete a comment (async)."""
        params = self._build_params(
            account_id=account_id,
            comment_id=comment_id,
        )
        data = await self._client._adelete(f"/v1/inbox/comments/{post_id}", params=params)
        return InboxActionResponse.model_validate(data)

    def hide_inbox_comment(self, post_id: str, comment_id: str, *, account_id: str) -> InboxHideResponse:
        """Hide a comment."""
        payload = self._build_payload(
            account_id=account_id,
        )
        data = self._client._post(f"/v1/inbox/comments/{post_id}/{comment_id}/hide", data=payload)
        return InboxHideResponse.model_validate(data)

    async def ahide_inbox_comment(self, post_id: str, comment_id: str, *, account_id: str) -> InboxHideResponse:
        """Hide a comment (async)."""
        payload = self._build_payload(
            account_id=account_id,
        )
        data = await self._client._apost(f"/v1/inbox/comments/{post_id}/{comment_id}/hide", data=payload)
        return InboxHideResponse.model_validate(data)

    def unhide_inbox_comment(self, post_id: str, comment_id: str, *, account_id: str) -> InboxHideResponse:
        """Unhide a comment."""
        params = self._build_params(
            account_id=account_id,
        )
        data = self._client._delete(f"/v1/inbox/comments/{post_id}/{comment_id}/hide", params=params)
        return InboxHideResponse.model_validate(data)

    async def aunhide_inbox_comment(self, post_id: str, comment_id: str, *, account_id: str) -> InboxHideResponse:
        """Unhide a comment (async)."""
        params = self._build_params(
            account_id=account_id,
        )
        data = await self._client._adelete(f"/v1/inbox/comments/{post_id}/{comment_id}/hide", params=params)
        return InboxHideResponse.model_validate(data)

    def list_inbox_conversations(self, *, account_id: str | None = None, profile_id: str | None = None, platform: str | None = None, status: str | None = None, sort_order: str | None = 'desc', limit: int | None = 50, cursor: str | None = None) -> InboxConversationsResponse:
        """List direct message conversations."""
        params = self._build_params(
            account_id=account_id,
            profile_id=profile_id,
            platform=platform,
            status=status,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )
        data = self._client._get('/v1/inbox/conversations', params=params)
        return InboxConversationsResponse.model_validate(data)

    async def alist_inbox_conversations(self, *, account_id: str | None = None, profile_id: str | None = None, platform: str | None = None, status: str | None = None, sort_order: str | None = 'desc', limit: int | None = 50, cursor: str | None = None) -> InboxConversationsResponse:
        """List direct message conversations (async)."""
        params = self._build_params(
            account_id=account_id,
            profile_id=profile_id,
            platform=platform,
            status=status,
            sort_order=sort_order,
            limit=limit,
            cursor=cursor,
        )
        data = await self._client._aget('/v1/inbox/conversations', params=params)
        return InboxConversationsResponse.model_validate(data)

    def search_inbox_conversations(self, *, query: str, direction: str | None = None, account_id: str | None = None, profile_id: str | None = None, platform: str | None = None, limit: int | None = 20, cursor: str | None = None) -> InboxConversationSearchResponse:
        """Search direct message conversations."""
        params = self._build_params(
            query=query,
            direction=direction,
            account_id=account_id,
            profile_id=profile_id,
            platform=platform,
            limit=limit,
            cursor=cursor,
        )
        data = self._client._get('/v1/inbox/conversations/search', params=params)
        return InboxConversationSearchResponse.model_validate(data)

    async def asearch_inbox_conversations(self, *, query: str, direction: str | None = None, account_id: str | None = None, profile_id: str | None = None, platform: str | None = None, limit: int | None = 20, cursor: str | None = None) -> InboxConversationSearchResponse:
        """Search direct message conversations (async)."""
        params = self._build_params(
            query=query,
            direction=direction,
            account_id=account_id,
            profile_id=profile_id,
            platform=platform,
            limit=limit,
            cursor=cursor,
        )
        data = await self._client._aget('/v1/inbox/conversations/search', params=params)
        return InboxConversationSearchResponse.model_validate(data)

    def get_inbox_conversation(self, conversation_id: str, *, account_id: str) -> InboxConversationResponse:
        """Get a direct message conversation."""
        params = self._build_params(
            account_id=account_id,
        )
        data = self._client._get(f"/v1/inbox/conversations/{conversation_id}", params=params)
        return InboxConversationResponse.model_validate(data)

    async def aget_inbox_conversation(self, conversation_id: str, *, account_id: str) -> InboxConversationResponse:
        """Get a direct message conversation (async)."""
        params = self._build_params(
            account_id=account_id,
        )
        data = await self._client._aget(f"/v1/inbox/conversations/{conversation_id}", params=params)
        return InboxConversationResponse.model_validate(data)

    def update_inbox_conversation(self, conversation_id: str, *, account_id: str, status: str) -> InboxConversationUpdateResponse:
        """Archive or unarchive a conversation."""
        payload = self._build_payload(
            account_id=account_id,
            status=status,
        )
        data = self._client._put(f"/v1/inbox/conversations/{conversation_id}", data=payload)
        return InboxConversationUpdateResponse.model_validate(data)

    async def aupdate_inbox_conversation(self, conversation_id: str, *, account_id: str, status: str) -> InboxConversationUpdateResponse:
        """Archive or unarchive a conversation (async)."""
        payload = self._build_payload(
            account_id=account_id,
            status=status,
        )
        data = await self._client._aput(f"/v1/inbox/conversations/{conversation_id}", data=payload)
        return InboxConversationUpdateResponse.model_validate(data)

    def mark_inbox_conversation_read(self, conversation_id: str, *, account_id: str) -> InboxConversationReadResponse:
        """Mark a conversation read."""
        payload = self._build_payload(
            account_id=account_id,
        )
        data = self._client._post(f"/v1/inbox/conversations/{conversation_id}/read", data=payload)
        return InboxConversationReadResponse.model_validate(data)

    async def amark_inbox_conversation_read(self, conversation_id: str, *, account_id: str) -> InboxConversationReadResponse:
        """Mark a conversation read (async)."""
        payload = self._build_payload(
            account_id=account_id,
        )
        data = await self._client._apost(f"/v1/inbox/conversations/{conversation_id}/read", data=payload)
        return InboxConversationReadResponse.model_validate(data)

    def list_inbox_conversation_messages(self, conversation_id: str, *, account_id: str, limit: int | None = 100, cursor: str | None = None, sort_order: str | None = 'asc') -> InboxMessagesResponse:
        """List messages in a conversation."""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            sort_order=sort_order,
        )
        data = self._client._get(f"/v1/inbox/conversations/{conversation_id}/messages", params=params)
        return InboxMessagesResponse.model_validate(data)

    async def alist_inbox_conversation_messages(self, conversation_id: str, *, account_id: str, limit: int | None = 100, cursor: str | None = None, sort_order: str | None = 'asc') -> InboxMessagesResponse:
        """List messages in a conversation (async)."""
        params = self._build_params(
            account_id=account_id,
            limit=limit,
            cursor=cursor,
            sort_order=sort_order,
        )
        data = await self._client._aget(f"/v1/inbox/conversations/{conversation_id}/messages", params=params)
        return InboxMessagesResponse.model_validate(data)

    def send_inbox_message(self, conversation_id: str, *, account_id: str, idempotency_key: str | None = None, message: str | None = None, attachment_url: str | None = None, attachment_type: str | None = None) -> InboxMessageSendResponse:
        """Send a direct message."""
        headers = self._build_headers(
            idempotency_key=idempotency_key,
        )
        payload = self._build_payload(
            account_id=account_id,
            message=message,
            attachment_url=attachment_url,
            attachment_type=attachment_type,
        )
        data = self._client._post(f"/v1/inbox/conversations/{conversation_id}/messages", data=payload, headers=headers)
        return InboxMessageSendResponse.model_validate(data)

    async def asend_inbox_message(self, conversation_id: str, *, account_id: str, idempotency_key: str | None = None, message: str | None = None, attachment_url: str | None = None, attachment_type: str | None = None) -> InboxMessageSendResponse:
        """Send a direct message (async)."""
        headers = self._build_headers(
            idempotency_key=idempotency_key,
        )
        payload = self._build_payload(
            account_id=account_id,
            message=message,
            attachment_url=attachment_url,
            attachment_type=attachment_type,
        )
        data = await self._client._apost(f"/v1/inbox/conversations/{conversation_id}/messages", data=payload, headers=headers)
        return InboxMessageSendResponse.model_validate(data)
