"""
Auto-generated media resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    MediaPresignResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class MediaResource(BaseResource[Any]):
    """Create presigned media upload URLs."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def create_media_presign(self, *, filename: str, content_type: str, size: int | None = None, profile_id: str | None = None) -> MediaPresignResponse:
        """Create a presigned media upload URL."""
        payload = self._build_payload(
            filename=filename,
            content_type=content_type,
            size=size,
            profile_id=profile_id,
        )
        data = self._client._post('/v1/media/presign', data=payload)
        return MediaPresignResponse.model_validate(data)

    async def acreate_media_presign(self, *, filename: str, content_type: str, size: int | None = None, profile_id: str | None = None) -> MediaPresignResponse:
        """Create a presigned media upload URL (async)."""
        payload = self._build_payload(
            filename=filename,
            content_type=content_type,
            size=size,
            profile_id=profile_id,
        )
        data = await self._client._apost('/v1/media/presign', data=payload)
        return MediaPresignResponse.model_validate(data)
