"""
Auto-generated profiles resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    MessageResponse,
    ProfileResponse,
    ProfileWriteResponse,
    ProfilesListResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class ProfilesResource(BaseResource[Any]):
    """Manage PostZen profiles."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_profiles(self) -> ProfilesListResponse:
        """List profiles."""
        data = self._client._get('/v1/profiles')
        return ProfilesListResponse.model_validate(data)

    async def alist_profiles(self) -> ProfilesListResponse:
        """List profiles (async)."""
        data = await self._client._aget('/v1/profiles')
        return ProfilesListResponse.model_validate(data)

    def create_profile(self, *, name: str, description: str | None = None, color: str | None = '#ffeda0') -> ProfileWriteResponse:
        """Create a profile."""
        payload = self._build_payload(
            name=name,
            description=description,
            color=color,
        )
        data = self._client._post('/v1/profiles', data=payload)
        return ProfileWriteResponse.model_validate(data)

    async def acreate_profile(self, *, name: str, description: str | None = None, color: str | None = '#ffeda0') -> ProfileWriteResponse:
        """Create a profile (async)."""
        payload = self._build_payload(
            name=name,
            description=description,
            color=color,
        )
        data = await self._client._apost('/v1/profiles', data=payload)
        return ProfileWriteResponse.model_validate(data)

    def get_profile(self, profile_id: str) -> ProfileResponse:
        """Get a profile."""
        data = self._client._get(f"/v1/profiles/{profile_id}")
        return ProfileResponse.model_validate(data)

    async def aget_profile(self, profile_id: str) -> ProfileResponse:
        """Get a profile (async)."""
        data = await self._client._aget(f"/v1/profiles/{profile_id}")
        return ProfileResponse.model_validate(data)

    def update_profile(self, profile_id: str, *, name: str | None = None, description: str | None = None, color: str | None = None, is_default: bool | None = None) -> ProfileWriteResponse:
        """Update a profile."""
        payload = self._build_payload(
            name=name,
            description=description,
            color=color,
            is_default=is_default,
        )
        data = self._client._put(f"/v1/profiles/{profile_id}", data=payload)
        return ProfileWriteResponse.model_validate(data)

    async def aupdate_profile(self, profile_id: str, *, name: str | None = None, description: str | None = None, color: str | None = None, is_default: bool | None = None) -> ProfileWriteResponse:
        """Update a profile (async)."""
        payload = self._build_payload(
            name=name,
            description=description,
            color=color,
            is_default=is_default,
        )
        data = await self._client._aput(f"/v1/profiles/{profile_id}", data=payload)
        return ProfileWriteResponse.model_validate(data)

    def delete_profile(self, profile_id: str) -> MessageResponse:
        """Delete a profile."""
        data = self._client._delete(f"/v1/profiles/{profile_id}")
        return MessageResponse.model_validate(data)

    async def adelete_profile(self, profile_id: str) -> MessageResponse:
        """Delete a profile (async)."""
        data = await self._client._adelete(f"/v1/profiles/{profile_id}")
        return MessageResponse.model_validate(data)
