"""
Auto-generated queues resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    QueueDeleteResponse,
    QueueNextSlotResponse,
    QueuePreviewResponse,
    QueueSlotsResponse,
    QueueUpdateResponse,
    QueueWriteResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from ...client.base import BaseClient


class QueuesResource(BaseResource[Any]):
    """Manage per-profile posting queues."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_queue_slots(self, *, profile_id: str, queue_id: str | None = None, all: bool | None = None) -> QueueSlotsResponse:
        """Get a queue schedule."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
            all=all,
        )
        data = self._client._get('/v1/queue/slots', params=params)
        return QueueSlotsResponse.model_validate(data)

    async def alist_queue_slots(self, *, profile_id: str, queue_id: str | None = None, all: bool | None = None) -> QueueSlotsResponse:
        """Get a queue schedule (async)."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
            all=all,
        )
        data = await self._client._aget('/v1/queue/slots', params=params)
        return QueueSlotsResponse.model_validate(data)

    def create_queue_slot(self, *, profile_id: str, timezone: str, slots: list[dict[str, Any]], name: str | None = 'Default Queue', description: str | None = None, active: bool | None = True, set_as_default: bool | None = None) -> QueueWriteResponse:
        """Create a queue."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            description=description,
            timezone=timezone,
            slots=slots,
            active=active,
            set_as_default=set_as_default,
        )
        data = self._client._post('/v1/queue/slots', data=payload)
        return QueueWriteResponse.model_validate(data)

    async def acreate_queue_slot(self, *, profile_id: str, timezone: str, slots: list[dict[str, Any]], name: str | None = 'Default Queue', description: str | None = None, active: bool | None = True, set_as_default: bool | None = None) -> QueueWriteResponse:
        """Create a queue (async)."""
        payload = self._build_payload(
            profile_id=profile_id,
            name=name,
            description=description,
            timezone=timezone,
            slots=slots,
            active=active,
            set_as_default=set_as_default,
        )
        data = await self._client._apost('/v1/queue/slots', data=payload)
        return QueueWriteResponse.model_validate(data)

    def update_queue_slot(self, *, profile_id: str, timezone: str, slots: list[dict[str, Any]], queue_id: str | None = None, name: str | None = None, description: str | None = None, active: bool | None = None, set_as_default: bool | None = None, reshuffle_existing: bool | None = None) -> QueueUpdateResponse:
        """Update a queue."""
        payload = self._build_payload(
            profile_id=profile_id,
            queue_id=queue_id,
            name=name,
            description=description,
            timezone=timezone,
            slots=slots,
            active=active,
            set_as_default=set_as_default,
            reshuffle_existing=reshuffle_existing,
        )
        data = self._client._put('/v1/queue/slots', data=payload)
        return QueueUpdateResponse.model_validate(data)

    async def aupdate_queue_slot(self, *, profile_id: str, timezone: str, slots: list[dict[str, Any]], queue_id: str | None = None, name: str | None = None, description: str | None = None, active: bool | None = None, set_as_default: bool | None = None, reshuffle_existing: bool | None = None) -> QueueUpdateResponse:
        """Update a queue (async)."""
        payload = self._build_payload(
            profile_id=profile_id,
            queue_id=queue_id,
            name=name,
            description=description,
            timezone=timezone,
            slots=slots,
            active=active,
            set_as_default=set_as_default,
            reshuffle_existing=reshuffle_existing,
        )
        data = await self._client._aput('/v1/queue/slots', data=payload)
        return QueueUpdateResponse.model_validate(data)

    def delete_queue_slot(self, *, profile_id: str, queue_id: str | None = None) -> QueueDeleteResponse:
        """Delete a queue."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
        )
        data = self._client._delete('/v1/queue/slots', params=params)
        return QueueDeleteResponse.model_validate(data)

    async def adelete_queue_slot(self, *, profile_id: str, queue_id: str | None = None) -> QueueDeleteResponse:
        """Delete a queue (async)."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
        )
        data = await self._client._adelete('/v1/queue/slots', params=params)
        return QueueDeleteResponse.model_validate(data)

    def get_next_queue_slot(self, *, profile_id: str, queue_id: str | None = None) -> QueueNextSlotResponse:
        """Get the next queue slot."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
        )
        data = self._client._get('/v1/queue/next-slot', params=params)
        return QueueNextSlotResponse.model_validate(data)

    async def aget_next_queue_slot(self, *, profile_id: str, queue_id: str | None = None) -> QueueNextSlotResponse:
        """Get the next queue slot (async)."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
        )
        data = await self._client._aget('/v1/queue/next-slot', params=params)
        return QueueNextSlotResponse.model_validate(data)

    def preview_queue(self, *, profile_id: str, queue_id: str | None = None, count: int | None = 20) -> QueuePreviewResponse:
        """Preview upcoming queue slots."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
            count=count,
        )
        data = self._client._get('/v1/queue/preview', params=params)
        return QueuePreviewResponse.model_validate(data)

    async def apreview_queue(self, *, profile_id: str, queue_id: str | None = None, count: int | None = 20) -> QueuePreviewResponse:
        """Preview upcoming queue slots (async)."""
        params = self._build_params(
            profile_id=profile_id,
            queue_id=queue_id,
            count=count,
        )
        data = await self._client._aget('/v1/queue/preview', params=params)
        return QueuePreviewResponse.model_validate(data)
