"""
Auto-generated webhooks resource.

DO NOT EDIT THIS FILE MANUALLY.
Run `python scripts/generate_resources.py` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ...models import (
    MessageResponse,
    WebhookDeliveriesListResponse,
    WebhookResponse,
    WebhookWriteResponse,
    WebhooksListResponse,
)

from ..base import BaseResource

if TYPE_CHECKING:
    from datetime import datetime
    from ...client.base import BaseClient


class WebhooksResource(BaseResource[Any]):
    """Manage outbound webhook endpoints and retained delivery logs."""

    def __init__(self, client: BaseClient) -> None:
        super().__init__(client)

    def list_webhooks(self) -> WebhooksListResponse:
        """List webhooks."""
        data = self._client._get('/v1/webhooks')
        return WebhooksListResponse.model_validate(data)

    async def alist_webhooks(self) -> WebhooksListResponse:
        """List webhooks (async)."""
        data = await self._client._aget('/v1/webhooks')
        return WebhooksListResponse.model_validate(data)

    def create_webhook(self, *, name: str, url: str, events: list[dict[str, Any]], profile_access: str, profile_ids: list[str] | None = None, secret: str | None = None, custom_headers: list[dict[str, Any]] | None = None, is_active: bool | None = True) -> WebhookWriteResponse:
        """Create a webhook."""
        payload = self._build_payload(
            name=name,
            url=url,
            events=events,
            profile_access=profile_access,
            profile_ids=profile_ids,
            secret=secret,
            custom_headers=custom_headers,
            is_active=is_active,
        )
        data = self._client._post('/v1/webhooks', data=payload)
        return WebhookWriteResponse.model_validate(data)

    async def acreate_webhook(self, *, name: str, url: str, events: list[dict[str, Any]], profile_access: str, profile_ids: list[str] | None = None, secret: str | None = None, custom_headers: list[dict[str, Any]] | None = None, is_active: bool | None = True) -> WebhookWriteResponse:
        """Create a webhook (async)."""
        payload = self._build_payload(
            name=name,
            url=url,
            events=events,
            profile_access=profile_access,
            profile_ids=profile_ids,
            secret=secret,
            custom_headers=custom_headers,
            is_active=is_active,
        )
        data = await self._client._apost('/v1/webhooks', data=payload)
        return WebhookWriteResponse.model_validate(data)

    def get_webhook(self, webhook_id: str) -> WebhookResponse:
        """Get a webhook."""
        data = self._client._get(f"/v1/webhooks/{webhook_id}")
        return WebhookResponse.model_validate(data)

    async def aget_webhook(self, webhook_id: str) -> WebhookResponse:
        """Get a webhook (async)."""
        data = await self._client._aget(f"/v1/webhooks/{webhook_id}")
        return WebhookResponse.model_validate(data)

    def update_webhook(self, webhook_id: str, *, name: str | None = None, url: str | None = None, events: list[dict[str, Any]] | None = None, profile_access: str | None = None, profile_ids: list[str] | None = None, secret: str | None = None, custom_headers: list[dict[str, Any]] | None = None, is_active: bool | None = None) -> WebhookWriteResponse:
        """Update a webhook."""
        payload = self._build_payload(
            name=name,
            url=url,
            events=events,
            profile_access=profile_access,
            profile_ids=profile_ids,
            secret=secret,
            custom_headers=custom_headers,
            is_active=is_active,
        )
        data = self._client._put(f"/v1/webhooks/{webhook_id}", data=payload)
        return WebhookWriteResponse.model_validate(data)

    async def aupdate_webhook(self, webhook_id: str, *, name: str | None = None, url: str | None = None, events: list[dict[str, Any]] | None = None, profile_access: str | None = None, profile_ids: list[str] | None = None, secret: str | None = None, custom_headers: list[dict[str, Any]] | None = None, is_active: bool | None = None) -> WebhookWriteResponse:
        """Update a webhook (async)."""
        payload = self._build_payload(
            name=name,
            url=url,
            events=events,
            profile_access=profile_access,
            profile_ids=profile_ids,
            secret=secret,
            custom_headers=custom_headers,
            is_active=is_active,
        )
        data = await self._client._aput(f"/v1/webhooks/{webhook_id}", data=payload)
        return WebhookWriteResponse.model_validate(data)

    def delete_webhook(self, webhook_id: str) -> MessageResponse:
        """Delete a webhook."""
        data = self._client._delete(f"/v1/webhooks/{webhook_id}")
        return MessageResponse.model_validate(data)

    async def adelete_webhook(self, webhook_id: str) -> MessageResponse:
        """Delete a webhook (async)."""
        data = await self._client._adelete(f"/v1/webhooks/{webhook_id}")
        return MessageResponse.model_validate(data)

    def test_webhook(self, webhook_id: str) -> dict[str, Any]:
        """Test a webhook."""
        data = self._client._post(f"/v1/webhooks/{webhook_id}/test")
        return data

    async def atest_webhook(self, webhook_id: str) -> dict[str, Any]:
        """Test a webhook (async)."""
        data = await self._client._apost(f"/v1/webhooks/{webhook_id}/test")
        return data

    def list_webhook_deliveries(self, *, webhook_id: str | None = None, event: str | None = None, status: str | None = None, date_from: datetime | str | None = None, date_to: datetime | str | None = None, page: int | None = 1, limit: int | None = 20) -> WebhookDeliveriesListResponse:
        """List webhook deliveries."""
        params = self._build_params(
            webhook_id=webhook_id,
            event=event,
            status=status,
            date_from=date_from,
            date_to=date_to,
            page=page,
            limit=limit,
        )
        data = self._client._get('/v1/webhook-deliveries', params=params)
        return WebhookDeliveriesListResponse.model_validate(data)

    async def alist_webhook_deliveries(self, *, webhook_id: str | None = None, event: str | None = None, status: str | None = None, date_from: datetime | str | None = None, date_to: datetime | str | None = None, page: int | None = 1, limit: int | None = 20) -> WebhookDeliveriesListResponse:
        """List webhook deliveries (async)."""
        params = self._build_params(
            webhook_id=webhook_id,
            event=event,
            status=status,
            date_from=date_from,
            date_to=date_to,
            page=page,
            limit=limit,
        )
        data = await self._client._aget('/v1/webhook-deliveries', params=params)
        return WebhookDeliveriesListResponse.model_validate(data)

    def redeliver_webhook_delivery(self, delivery_id: str) -> dict[str, Any]:
        """Redeliver a webhook event."""
        data = self._client._post(f"/v1/webhook-deliveries/{delivery_id}/redeliver")
        return data

    async def aredeliver_webhook_delivery(self, delivery_id: str) -> dict[str, Any]:
        """Redeliver a webhook event (async)."""
        data = await self._client._apost(f"/v1/webhook-deliveries/{delivery_id}/redeliver")
        return data
